"""
Mixture of Experts Long Short-Term Memory (MixLSTM) Model.

This module contains the implementation of the MixLSTM and its baseline comparison model.
The underlying Mixture of Experts (MoE) architecture and gating mechanisms are adapted 
from the original MixLSTM implementation.

Reference: https://gitlab.eecs.umich.edu/mld3/mlhc2019_relaxed_parameter_sharing
           https://arxiv.org/abs/1906.02898
"""

from typing import Optional, Tuple, Callable, List, Union
import math
import torch
import torch.nn as nn
from collections import abc
from pyhealth.models import BaseModel

###########################################################################
# Part 1: Mixture of Experts (MoE) Base Classes & Gating Mechanisms
###########################################################################
class MoE(nn.Module):
    """Abstract base class for Mixture of Experts (MoE).
    
    This class supports specifying the expert networks and the gating function.
    It requires combining functions (implemented in subclasses like MoO or MoW).

    Args:
        experts (Union[nn.ModuleList, nn.Module]): The expert models.
        gate (nn.Module): The gating function/network.
    """
    def __init__(self, experts, gate):
        super(MoE, self).__init__()        
        self.experts = experts
        self.gate = gate

class MoO(MoE):
    """Mixture of Outputs (MoO) module.
    
    Combines the outputs of multiple experts using the coefficients 
    generated by the gating function.

    Args:
        experts (nn.ModuleList): A list of expert models.
        gate (nn.Module): The gating function/network.
        bs_dim (int, optional): The batch size dimension index. Defaults to 1 for RNNs.
        expert_dim (int, optional): The expert dimension index. Defaults to 0.
    """
    def __init__(self, experts, gate, bs_dim=1, expert_dim=0):
        super(MoO, self).__init__(experts, gate)        
        self.bs_dim = bs_dim
        self.expert_dim = expert_dim

    def combine(self, o: Union[List[torch.Tensor], Tuple], coef: torch.Tensor) -> torch.Tensor:
        """Combines expert outputs based on gating coefficients."""
        if isinstance(o[0], abc.Sequence): 
            return [self.combine(o_, coef) for o_ in zip(*o)]
        else:
            o = torch.stack(o)
            o = o.transpose(self.expert_dim, -1)
            o = o.transpose(self.bs_dim, -2) 

            res = o * coef
            res = res.transpose(self.expert_dim, -1)
            res = res.transpose(self.bs_dim, -2)
            return res.sum(0)
        
    def forward(self, x: torch.Tensor, coef: Optional[torch.Tensor] = None) -> torch.Tensor:
        """Forward pass for Mixture of Outputs."""
        coef = self.gate(x, coef)
        self.last_coef = coef
        o = [expert(x) for expert in self.experts]
        return self.combine(o, coef)

class MoW(MoE):
    """Mixture of Weights (MoW) module."""
    def forward(self, x: torch.Tensor, coef: Optional[torch.Tensor] = None) -> torch.Tensor:
        """Forward pass for Mixture of Weights.""" 
        coef = self.gate(x, coef)
        self.last_coef = coef
        return self.experts(x, coef)

class Gate(nn.Module):
    """Abstract base class for gate functions in the Mixture of Experts."""
    def forward(self, x: torch.Tensor, coef: Optional[torch.Tensor] = None) -> torch.Tensor:
        raise NotImplementedError()

class NonAdaptiveGate(Gate):
    """Gate with fixed or learnable non-adaptive coefficients."""
    def __init__(self, num_experts, coef=None, fixed=False, normalize=False):
        super(self.__class__, self).__init__()
        self.normalize = normalize
        if coef is None: # initialization
            coef = torch.ones(num_experts)
            nn.init.uniform_(coef)
        if fixed:
            coef = nn.Parameter(coef, requires_grad=False)
        else:
            coef = nn.Parameter(coef)

        self.coefficients = coef

    def forward(self, x: torch.Tensor, coef: Optional[torch.Tensor] = None) -> torch.Tensor:
        """Computes the gating coefficients."""
        if self.normalize:
            return nn.functional.softmax(self.coefficients, 0)
        else:
            return self.coefficients
        
class IDGate(Gate): 
    """Identity gate that simply passes through the previous coefficients."""
    def forward(self, x: torch.Tensor, coef: torch.Tensor) -> torch.Tensor:
        return coef

def moo_linear(in_features, out_features, num_experts, bs_dim=1, expert_dim=0):
    """Creates a Mixture of Outputs (MoO) linear layer."""
    experts = nn.ModuleList()
    for _ in range(num_experts):
        experts.append(nn.Linear(in_features, out_features))   
    return MoO(experts, IDGate(), bs_dim=bs_dim, expert_dim=expert_dim) 

###########################################################################
# Part 2: Core LSTM Architectures with Expert Integration
###########################################################################
class MowLSTMLayer(nn.Module):
    """A single LSTM layer utilizing mixture of experts for its gates."""
    def __init__(self, input_size, hidden_size, num_experts=2, batch_first=False):

        super(MowLSTMLayer, self).__init__()
        
        self.input_size = input_size
        self.hidden_size = hidden_size
        self.num_experts = num_experts
        self.batch_first = batch_first

        self.input_weights = moo_linear(input_size, 4 * hidden_size,
                                        self.num_experts, bs_dim=2)
        self.hidden_weights = moo_linear(hidden_size, 4 * hidden_size,
                                         self.num_experts, bs_dim=2)

        stdv = 1.0 / math.sqrt(self.hidden_size)
        for m in self.input_weights.experts:
            for name, weight in m.named_parameters():
                nn.init.uniform_(weight, -stdv, stdv)
                # if 'weight' in name:
                #     nn.init.uniform_(weight)
        for m in self.hidden_weights.experts:
            for name, weight in m.named_parameters():
                nn.init.uniform_(weight, -stdv, stdv) 
                # if 'weight' in name:
                #     nn.init.orthogonal_(weight)

    def rnn_step(
        self, 
        x: torch.Tensor, 
        hidden: Tuple[torch.Tensor, torch.Tensor], 
        coef: torch.Tensor
    ) -> Tuple[torch.Tensor, torch.Tensor]: 
        """Performs one step of the RNN computation."""
        bs = x.shape[1]              
        h, c = hidden
        gates = self.input_weights(x, coef) + self.hidden_weights(h, coef)

        ingate, forgetgate, cellgate, outgate = gates.view(bs, -1).chunk(4, 1)
        ingate = torch.sigmoid(ingate)
        forgetgate = torch.sigmoid(forgetgate)
        cellgate = torch.tanh(cellgate)
        outgate = torch.sigmoid(outgate)

        c = forgetgate * c + ingate * cellgate
        h = outgate * torch.tanh(c)
        return h, c
    
    def forward(
        self, 
        x: torch.Tensor, 
        hidden: Tuple[torch.Tensor, torch.Tensor], 
        coef: torch.Tensor
    ) -> Tuple[torch.Tensor, Tuple[torch.Tensor, torch.Tensor]]:
        """Forward pass through the time sequence."""
        if self.batch_first: # change to seq_len first
            x = x.transpose(0, 1)

        seq_len = x.shape[0]
        output = []
        for t in range(seq_len):
            hidden = self.rnn_step(x[t].unsqueeze(0), hidden, coef)
            output.append(hidden[0]) 

        output = torch.cat(output, 0)
        return output, hidden

class MowLSTM(nn.Module):
    """Responsible for stacking and creating bidirectional MowLSTM layers."""
    def __init__(self, input_size, hidden_size, num_classes, num_experts=2,
                 num_layers=1, batch_first=False, dropout=0, bidirectional=False,
                 activation=None):

        super(MowLSTM, self).__init__()
        
        self.input_size = input_size
        self.hidden_size = hidden_size
        self.num_classes = num_classes
        self.num_experts = num_experts
        self.num_layers = num_layers
        self.num_directions = 2 if bidirectional else 1
        self.batch_first = batch_first
        self.dropouts = nn.ModuleList()

        self.h2o = moo_linear(self.num_directions * self.hidden_size,
                              self.num_classes, self.num_experts, bs_dim=2)
        
        if activation:
            self.activation = activation
        else:
            self.activation = lambda x: x
        
        self.rnns = nn.ModuleList()
        for i in range(num_layers * self.num_directions):
            input_size = input_size if i == 0 else hidden_size
            self.rnns.append(MowLSTMLayer(input_size, hidden_size, num_experts, batch_first))
            self.dropouts.append(nn.Dropout(p=dropout))

    def forward(
        self, 
        x: Tuple[torch.Tensor, Tuple[torch.Tensor, torch.Tensor]], 
        coef: torch.Tensor
    ) -> Tuple[torch.Tensor, Tuple[torch.Tensor, torch.Tensor]]:
        """Forward pass for stacked/bidirectional MowLSTM."""
        x, hidden = x
        self.last_coef = coef
        
        h, c = hidden
        hs, cs = [], []
        for i in range(self.num_layers):
            if i != 0 and i != (self.num_layers - 1):
                x = self.dropouts[i](x) # waste 1 droput out but no problem
            x, hidden = self.rnns[i](x, (h[i].unsqueeze(0), c[i].unsqueeze(0)), coef)
            hs.append(hidden[0])
            cs.append(hidden[1])      


        h = torch.cat(hs, 0)
        c = torch.cat(cs, 0)
        o = x
  
        o = self.dropouts[0](o)
        o = self.h2o(o, coef)
        o = self.activation(o)

        return o, (h, c)

class BaseModelLSTM(nn.Module):
    """Standard LSTM model used as a comparative baseline within PyHealth."""
    def __init__(self, input_size, hidden_size, output_size, num_layers=1,
                 num_directions=1, dropout=0, activation=None):
        super(BaseModelLSTM, self).__init__()
        self.input_size = input_size
        self.hidden_size = hidden_size
        self.output_size = output_size
        self.num_layers = num_layers
        self.dropout = dropout
        if dropout != 0:
            self.drop = nn.Dropout(p=dropout)
        self.bidirectional = (num_directions == 2)
        self.model = torch.nn.LSTM(self.input_size, self.hidden_size,
                                   num_layers=num_layers,
                                   bidirectional=self.bidirectional,
                                   dropout=dropout)
        self.h2o = nn.Linear(hidden_size * num_directions, output_size)
        self.softmax = nn.LogSoftmax(dim=1)
        if activation:
            self.activation = activation
        else:
            self.activation = lambda x: x

    def forward(
        self, 
        x: Tuple[torch.Tensor, Tuple[torch.Tensor, torch.Tensor]]
    ) -> Tuple[torch.Tensor, Tuple[torch.Tensor, torch.Tensor]]:
        """Forward pass for the baseline LSTM."""
        x, hidden = x
        
        # x.shape: (seq_len, bs, _)
        o, hidden = self.model(x, hidden)

        if type(x) is torch.nn.utils.rnn.PackedSequence:
            # undo packing: second arg is input_lengths (we do not need)
            # o: seq_len x bs x d            
            o, _ = torch.nn.utils.rnn.pad_packed_sequence(o)
            
        seq_len, bs, d  = o.shape
        # dim transformation: (seq_len, bs, d) -> (seq_len x bs, d)
        o = o.view(-1, o.shape[2])

        if self.dropout != 0:
            o = self.drop(o)
        
        # run through prediction layer
        o = self.h2o(o)
        o = self.activation(o)

        # dim transformation
        o = o.view(seq_len, bs, self.output_size)

        return o, hidden
    
class ExampleMowLSTM(nn.Module):
    """Wrapper to recreate the full MixLSTM architecture with time-unrolled experts."""    
    def __init__(self, input_size, hidden_size, num_classes,
                 num_layers=1, num_directions=1, dropout=0, activation=None):
        super(ExampleMowLSTM, self).__init__()
        self.input_size = input_size
        self.hidden_size = hidden_size
        self.num_classes = num_classes
        self.num_layers = num_layers
        self.num_directions = num_directions
        self.dropout = dropout
        self.activation = activation

    def set_kt(self, k, t): # k models t steps
        """Sets up K experts across T maximum time steps."""
        self.k = k
        self.T = t
        self.cells = nn.ModuleList()

        experts = MowLSTM(self.input_size, self.hidden_size,
                          self.num_classes, num_experts=self.k,
                          num_layers=self.num_layers, dropout=self.dropout,
                          bidirectional = (self.num_directions==2),
                          activation=self.activation)
        self.experts = experts
        
        for _ in range(t):
            gate = NonAdaptiveGate(self.k, normalize=True)
            # gate = AdaptiveLSTMGate(self.hidden_size *\
            #                         self.num_layers *\
            #                         self.num_directions,
            #                         self.k,
            #                         normalize=True)
            self.cells.append(MoW(experts, gate))

    def forward(
        self, 
        x: torch.Tensor, 
        hidden: Tuple[torch.Tensor, torch.Tensor], 
        input_lengths: List[int]
    ) -> Tuple[torch.Tensor, Tuple[torch.Tensor, torch.Tensor]]:
        """Forward pass unrolling the gating mechanism over time."""
        seq_len, bs, _ = x.shape
        o = []
        for t in range(seq_len):
            o_, hidden = self.cells[t]((x[t].view(1, bs, -1), hidden))
            o.append(o_)
            
        o = torch.cat(o, 0) # (seq_len, bs, d)
        return o, hidden

###########################################################################
# Part 3: PyHealth BaseModel Wrappers
###########################################################################
class MixLSTM(BaseModel):
    """Mixture of Experts Long Short-Term Memory (MixLSTM) model.
    
    This model implements the MixLSTM architecture for clinical time-series prediction,
    utilizing a mixture of experts with gating mechanisms to capture complex temporal dynamics,
    particularly suited for irregular and imbalanced clinical data.
    
    Args:
        dataset: The PyHealth dataset object.
        input_size (int): The dimensionality of the input features. Defaults to 76.
        hidden_size (int): The number of features in the hidden state. Defaults to 128.
        num_experts (int): The number of expert LSTM cells. Defaults to 2.
        max_seq_len (int): The maximum sequence length for target replication. Defaults to 48.
        **kwargs: Additional keyword arguments.
    Example:
        >>> from pyhealth.datasets import SampleEHRDataset
        >>> dataset = SampleEHRDataset()
        >>> model = MixLSTM(dataset=dataset, input_size=76, hidden_size=128)
        >>> # Assuming 'data_batch' is obtained from a PyHealth DataLoader
        >>> res = model(**data_batch)
        >>> print(res["y_prob"].shape)
    """
    def __init__(self, dataset, input_size=76,hidden_size=128, num_experts=2, max_seq_len=48, **kwargs):
        super().__init__(dataset=dataset)
        
        if hasattr(dataset, "input_schema") and "physio_features" in dataset.input_schema:
            self.input_size = dataset.input_schema["physio_features"].dim
        else:
            self.input_size = input_size
        self.output_size = self.get_output_size()
        
        self.hidden_size = hidden_size
        self.num_experts = num_experts
        self.max_seq_len = max_seq_len
        
        self.model = ExampleMowLSTM(
            input_size=self.input_size, 
            hidden_size=self.hidden_size,
            num_classes=self.output_size, 
            num_layers=1,
            num_directions=1,
            dropout=0,
            activation=None
        )
        
        self.model.set_kt(self.num_experts, self.max_seq_len)

    def forward(self, **kwargs) -> dict:
        """Forward pass conforming to PyHealth BaseModel standards."""
        x = kwargs[self.feature_keys[0]]
        batch_size = x.size(0)
        seq_len = x.size(1)
        
        x_permuted = x.permute(1, 0, 2)
        input_lengths = [seq_len] * batch_size 

        h = torch.zeros(1, batch_size, self.hidden_size, device=self.device)
        c = torch.zeros(1, batch_size, self.hidden_size, device=self.device)
        states = (h, c)
        
        outputs, _ = self.model(x_permuted, states, input_lengths)
        logits_seq = outputs.permute(1, 0, 2)

        res = {}

        if self.label_keys[0] in kwargs:
            y_true = kwargs[self.label_keys[0]]
            y_true_replicated = y_true.unsqueeze(1).repeat(1, seq_len, 1)
            loss_fn = self.get_loss_function()

            loss = loss_fn(
                logits_seq.reshape(-1, self.output_size), 
                y_true_replicated.reshape(-1, 1).float() if self.mode == "binary" else y_true_replicated.view(-1)
            )
            res["loss"] = loss
            res["y_true"] = y_true

        logits_max, _ = torch.max(logits_seq, dim=1) 
        y_prob_max = self.prepare_y_prob(logits_max) 
        
        res["logit"] = logits_max
        res["y_prob"] = y_prob_max
            
        return res

class BaselineLSTM(BaseModel):
    """Standard LSTM baseline model designed for fair comparison against MixLSTM.
    
    Args:
        dataset: The PyHealth dataset object.
        input_size (int): The dimensionality of the input features. Defaults to 76.
        hidden_size (int): The number of features in the hidden state. Defaults to 128.
        max_seq_len (int): The maximum sequence length. Defaults to 48.
        **kwargs: Additional keyword arguments.
    """
    def __init__(self, dataset, input_size=76, hidden_size=128, max_seq_len=48, **kwargs):
        super().__init__(dataset=dataset)
        
        if hasattr(dataset, "input_schema") and "physio_features" in dataset.input_schema:
            self.input_size = dataset.input_schema["physio_features"].dim
        else:
            self.input_size = input_size
        self.output_size = self.get_output_size()
        self.hidden_size = hidden_size
        self.max_seq_len = max_seq_len
        
        self.model = BaseModelLSTM(
            input_size=self.input_size, 
            hidden_size=self.hidden_size,
            output_size=self.output_size, 
            num_layers=1,
            num_directions=1,
            dropout=0,
            activation=None
        )

    def forward(self, **kwargs) -> dict:
        """Forward pass conforming to PyHealth BaseModel standards."""
        x = kwargs[self.feature_keys[0]]
        batch_size = x.size(0)
        seq_len = x.size(1)
        
        x_permuted = x.permute(1, 0, 2)
        
        h = torch.zeros(1, batch_size, self.hidden_size, device=self.device)
        c = torch.zeros(1, batch_size, self.hidden_size, device=self.device)
        states = (h, c)
        
        outputs, _ = self.model((x_permuted, states))
        logits_seq = outputs.permute(1, 0, 2)
        
        res = {}
        
        if self.label_keys[0] in kwargs:
            y_true = kwargs[self.label_keys[0]]
            y_true_replicated = y_true.unsqueeze(1).repeat(1, seq_len, 1)
            
            loss_fn = self.get_loss_function()
            loss = loss_fn(
                logits_seq.reshape(-1, self.output_size), 
                y_true_replicated.reshape(-1, 1).float() if self.mode == "binary" else y_true_replicated.view(-1)
            )
            res["loss"] = loss
            res["y_true"] = y_true

        logits_max, _ = torch.max(logits_seq, dim=1)
        y_prob_max = self.prepare_y_prob(logits_max)
        
        res["logit"] = logits_max
        res["y_prob"] = y_prob_max
            
        return res

       