"""
Utility functions for synthetic EHR generation.

This module provides helper functions for converting between different
representations of EHR data, particularly for working with synthetic
data generation baselines.
"""

import pandas as pd
from typing import List, Dict, Any


# Configuration
VISIT_DELIM = "VISIT_DELIM"


def tabular_to_sequences(df: pd.DataFrame, visit_delim: str = VISIT_DELIM) -> List[str]:
    """Convert tabular EHR DataFrame to text sequences.

    Converts a long-form EHR DataFrame (one row per diagnosis code) into
    patient sequences formatted as space-separated text with visit delimiters.

    Order: Group by SUBJECT_ID -> Sort/Group by HADM_ID -> Collect Codes

    Args:
        df: DataFrame with columns SUBJECT_ID, HADM_ID, ICD9_CODE
        visit_delim: Token to use as visit delimiter. Default is "VISIT_DELIM"

    Returns:
        List of text sequences, one per patient. Each sequence contains
        codes separated by spaces, with visits separated by the delimiter.

    Example:
        >>> df = pd.DataFrame({
        ...     'SUBJECT_ID': [1, 1, 1, 2, 2],
        ...     'HADM_ID': [100, 100, 200, 300, 300],
        ...     'ICD9_CODE': ['410', '250', '410', '250', '401']
        ... })
        >>> sequences = tabular_to_sequences(df)
        >>> print(sequences[0])
        '410 250 VISIT_DELIM 410'
    """
    # 1. Clean data: Ensure IDs are integers/strings (handle the .0 issue)
    df = df.copy()
    df["SUBJECT_ID"] = df["SUBJECT_ID"].astype(int)
    df["HADM_ID"] = df["HADM_ID"].astype(int)
    df["ICD9_CODE"] = df["ICD9_CODE"].astype(str)

    # 2. Aggregation Helper
    # This creates a list of codes for each admission
    # Note: In real scenarios, ensure you sort by ADMITTIME before this step!
    visits = (
        df.groupby(["SUBJECT_ID", "HADM_ID"])["ICD9_CODE"].apply(list).reset_index()
    )

    # 3. Create Patient Sequences
    # Group visits by patient and join them with the delimiter
    patient_seqs = []

    # We iterate by patient to preserve structure
    for subject_id, subject_data in visits.groupby("SUBJECT_ID"):
        # subject_data is a DataFrame of visits for one patient
        patient_history = []

        for codes_list in subject_data["ICD9_CODE"]:
            # Join codes within one visit (e.g., "code1 code2")
            visit_str = " ".join(codes_list)
            patient_history.append(visit_str)

        # Join all visits with the delimiter
        full_seq = f" {visit_delim} ".join(patient_history)
        patient_seqs.append(full_seq)

    return patient_seqs


def sequences_to_tabular(
    sequences: List[str], visit_delim: str = VISIT_DELIM
) -> pd.DataFrame:
    """Convert text sequences back to long-form DataFrame.

    Converts list of text sequences (generated by models) back into a
    long-form DataFrame with synthetic SUBJECT_ID and HADM_ID.

    Args:
        sequences: List of text sequences, one per patient
        visit_delim: Token used as visit delimiter. Default is "VISIT_DELIM"

    Returns:
        DataFrame with columns SUBJECT_ID, HADM_ID, ICD9_CODE

    Example:
        >>> sequences = ['410 250 VISIT_DELIM 410', '250 401']
        >>> df = sequences_to_tabular(sequences)
        >>> print(df)
           SUBJECT_ID  HADM_ID ICD9_CODE
        0           0        0       410
        1           0        0       250
        2           0        1       410
        3           1        0       250
        4           1        0       401
    """
    data_rows = []

    for subj_idx, seq in enumerate(sequences):
        # 1. Split sequence into visits
        # We strip to remove leading/trailing spaces
        visits = seq.strip().split(visit_delim)

        for hadm_idx, visit_str in enumerate(visits):
            # 2. Split visit into individual codes
            codes = visit_str.strip().split()

            # 3. Create a row for each code
            for code in codes:
                if code:  # Check if code is not empty string
                    data_rows.append(
                        {
                            "SUBJECT_ID": subj_idx,  # Synthetic Patient ID
                            "HADM_ID": hadm_idx,  # Synthetic Visit ID
                            "ICD9_CODE": code,
                        }
                    )

    return pd.DataFrame(data_rows)


def nested_codes_to_sequences(
    nested_codes: List[List[List[str]]], visit_delim: str = VISIT_DELIM
) -> List[str]:
    """Convert nested code structure to text sequences.

    Converts the nested structure from PyHealth models (list of patients,
    each containing list of visits, each containing list of codes) into
    text sequences.

    Args:
        nested_codes: List of patients, each containing visits, each containing codes
        visit_delim: Token used as visit delimiter. Default is "VISIT_DELIM"

    Returns:
        List of text sequences, one per patient

    Example:
        >>> nested = [[['410', '250'], ['410']], [['250', '401']]]
        >>> sequences = nested_codes_to_sequences(nested)
        >>> print(sequences[0])
        '410 250 VISIT_DELIM 410'
    """
    sequences = []

    for patient_visits in nested_codes:
        visit_strings = []
        for visit_codes in patient_visits:
            # Join codes within visit
            visit_str = " ".join([str(c) for c in visit_codes if c])
            if visit_str:  # Only add non-empty visits
                visit_strings.append(visit_str)

        # Join visits with delimiter
        full_seq = f" {visit_delim} ".join(visit_strings)
        sequences.append(full_seq)

    return sequences


def sequences_to_nested_codes(
    sequences: List[str], visit_delim: str = VISIT_DELIM
) -> List[List[List[str]]]:
    """Convert text sequences to nested code structure.

    Converts text sequences into nested structure (list of patients,
    each containing list of visits, each containing list of codes).

    Args:
        sequences: List of text sequences, one per patient
        visit_delim: Token used as visit delimiter. Default is "VISIT_DELIM"

    Returns:
        List of patients, each containing visits, each containing codes

    Example:
        >>> sequences = ['410 250 VISIT_DELIM 410', '250 401']
        >>> nested = sequences_to_nested_codes(sequences)
        >>> print(nested[0])
        [['410', '250'], ['410']]
    """
    nested_codes = []

    for seq in sequences:
        # Split sequence into visits
        visits = seq.strip().split(visit_delim)

        patient_visits = []
        for visit_str in visits:
            # Split visit into codes
            codes = visit_str.strip().split()
            if codes:  # Only add non-empty visits
                patient_visits.append(codes)

        nested_codes.append(patient_visits)

    return nested_codes


def create_flattened_representation(
    df: pd.DataFrame, drop_subject_id: bool = True
) -> pd.DataFrame:
    """Create flattened patient-level representation (crosstab).

    Converts long-form EHR data into a patient-level matrix where each
    row is a patient and each column is a diagnosis code count.

    This representation is used by baseline models like GReaT, CTGAN, TVAE.

    Args:
        df: DataFrame with columns SUBJECT_ID and ICD9_CODE
        drop_subject_id: Whether to drop SUBJECT_ID column. Default is True.

    Returns:
        DataFrame where rows are patients and columns are diagnosis codes

    Example:
        >>> df = pd.DataFrame({
        ...     'SUBJECT_ID': [1, 1, 2, 2, 2],
        ...     'ICD9_CODE': ['410', '250', '410', '410', '401']
        ... })
        >>> flattened = create_flattened_representation(df)
        >>> print(flattened)
           250  401  410
        0    1    0    1
        1    0    1    2
    """
    df = df.copy()
    df["ICD9_CODE"] = df["ICD9_CODE"].astype(str)

    # Remove NaN codes
    df = df.dropna(subset=["ICD9_CODE"])
    df = df[df["ICD9_CODE"] != "nan"]

    # Create crosstab
    result_df = pd.crosstab(df["SUBJECT_ID"], df["ICD9_CODE"]).reset_index()
    result_df.columns.name = None

    # Drop NaN column if exists
    if "nan" in result_df.columns:
        result_df = result_df.drop(columns=["nan"])

    if drop_subject_id:
        result_df = result_df.drop(columns=["SUBJECT_ID"])

    return result_df


def process_mimic_for_generation(
    mimic_data_path: str,
    train_patients_path: str = None,
    test_patients_path: str = None,
) -> Dict[str, Any]:
    """Process MIMIC data for synthetic generation tasks.

    Loads and processes MIMIC data, creating both sequential and flattened
    representations suitable for different baseline models.

    Args:
        mimic_data_path: Path to MIMIC data directory
        train_patients_path: Path to file containing train patient IDs (one per line)
        test_patients_path: Path to file containing test patient IDs (one per line)

    Returns:
        Dictionary containing:
            - train_ehr: Training data (long-form)
            - test_ehr: Test data (long-form)
            - train_flattened: Training data (patient-level matrix)
            - test_flattened: Test data (patient-level matrix)
            - train_sequences: Training data (text sequences)
            - test_sequences: Test data (text sequences)
    """
    import os

    # Load MIMIC data
    admissions_df = pd.read_csv(os.path.join(mimic_data_path, "ADMISSIONS.csv"))
    patients_df = pd.read_csv(os.path.join(mimic_data_path, "PATIENTS.csv"))
    diagnoses_df = pd.read_csv(os.path.join(mimic_data_path, "DIAGNOSES_ICD.csv"))

    print(f"Admissions shape: {admissions_df.shape}")
    print(f"Patients shape: {patients_df.shape}")
    print(f"Diagnoses shape: {diagnoses_df.shape}")

    # Parse dates
    admissions_df["ADMITTIME"] = pd.to_datetime(admissions_df["ADMITTIME"])
    patients_df["DOB"] = pd.to_datetime(patients_df["DOB"])

    # Calculate age at first admission
    first_admissions = admissions_df.loc[
        admissions_df.groupby("SUBJECT_ID")["ADMITTIME"].idxmin()
    ][["SUBJECT_ID", "ADMITTIME"]]

    demo_df = pd.merge(
        patients_df[["SUBJECT_ID", "GENDER", "DOB"]],
        first_admissions,
        on="SUBJECT_ID",
        how="inner",
    )

    demo_df["AGE"] = demo_df["ADMITTIME"].dt.year - demo_df["DOB"].dt.year
    demo_df["AGE"] = demo_df["AGE"].apply(lambda x: 90 if x > 89 else x)

    # Merge admissions with diagnoses
    admissions_info = admissions_df[["SUBJECT_ID", "HADM_ID", "ADMITTIME"]]
    merged_df = pd.merge(
        admissions_info,
        diagnoses_df[["SUBJECT_ID", "HADM_ID", "ICD9_CODE"]],
        on=["SUBJECT_ID", "HADM_ID"],
        how="inner",
    )

    # Merge with demographics
    final_df = pd.merge(
        merged_df,
        demo_df[["SUBJECT_ID", "AGE", "GENDER"]],
        on="SUBJECT_ID",
        how="left",
    )

    # Sort chronologically
    final_df.sort_values(by=["SUBJECT_ID", "ADMITTIME"], inplace=True)

    # Map HADM_ID to sequential visit IDs per patient
    final_df["VISIT_ID"] = final_df.groupby("SUBJECT_ID")["HADM_ID"].transform(
        lambda x: pd.factorize(x)[0]
    )

    final_df["SUBJECT_ID"] = final_df["SUBJECT_ID"].astype(str)
    final_df["HADM_ID"] = final_df["HADM_ID"].astype(float)
    final_df["ICD9_CODE"] = final_df["ICD9_CODE"].astype(str)

    # Keep only essential columns
    final_df = final_df[["SUBJECT_ID", "HADM_ID", "ICD9_CODE"]]
    final_df = final_df.dropna()

    result = {}

    # Split by train and test if provided
    if train_patients_path is not None and test_patients_path is not None:
        train_patient_ids = (
            pd.read_csv(train_patients_path, header=None)[0].astype(str)
        )
        test_patient_ids = (
            pd.read_csv(test_patients_path, header=None)[0].astype(str)
        )

        train_ehr = final_df[final_df["SUBJECT_ID"].isin(train_patient_ids)].reset_index(
            drop=True
        )
        test_ehr = final_df[final_df["SUBJECT_ID"].isin(test_patient_ids)].reset_index(
            drop=True
        )

        result["train_ehr"] = train_ehr
        result["test_ehr"] = test_ehr

        # Create flattened representations
        result["train_flattened"] = create_flattened_representation(train_ehr)
        result["test_flattened"] = create_flattened_representation(test_ehr)

        # Create sequences
        result["train_sequences"] = tabular_to_sequences(train_ehr)
        result["test_sequences"] = tabular_to_sequences(test_ehr)
    else:
        result["full_ehr"] = final_df
        result["full_flattened"] = create_flattened_representation(final_df)
        result["full_sequences"] = tabular_to_sequences(final_df)

    return result
