"""Unit tests for LUDB dataset and ECGWaveSegmentation task.

Author: Anton Barchukov

Tests cover:
    - LUDBDataset instantiation from wfdb files
    - Metadata preparation (prepare_metadata)
    - Patient header parsing (age, sex, diagnoses)
    - ECGWaveSegmentation task (windowing, trimming, labels)
    - Full pipeline: dataset -> task -> samples
    - MedTsLLM model with the LUDB data structure

Test data under ``test-resources/core/ludb/data/`` is fully synthetic
— records generated by ``tests/core/_synthetic_wfdb.synthesize_ludb``
with random ECG-shaped signals and placeholder demographics. No real
patient records are committed to the repo.
"""

import os
import unittest

import numpy as np
import torch

TEST_DATA_DIR = os.path.join(
    os.path.dirname(__file__), "..", "..", "test-resources", "core", "ludb"
)
HAS_TEST_DATA = os.path.isdir(os.path.join(TEST_DATA_DIR, "data"))


def setUpModule():
    """Drop the committed CSV + cache so tests use the current schema."""
    if HAS_TEST_DATA:
        _force_regenerate_metadata()


@unittest.skipUnless(HAS_TEST_DATA, "LUDB test data not found")
class TestLUDBDataset(unittest.TestCase):
    """Tests for LUDBDataset with real wfdb files."""

    @classmethod
    def setUpClass(cls):
        from pyhealth.datasets.ludb import LUDBDataset

        cls.dataset = LUDBDataset(root=TEST_DATA_DIR, dev=True)

    def test_dataset_loads(self):
        """Dataset initializes without error."""
        self.assertIsNotNone(self.dataset)

    def test_metadata_csv_created(self):
        """prepare_metadata creates ludb-pyhealth.csv."""
        csv_path = os.path.join(TEST_DATA_DIR, "ludb-pyhealth.csv")
        self.assertTrue(os.path.exists(csv_path))

    def test_has_patients(self):
        """Dataset has at least 1 patient."""
        pids = self.dataset.unique_patient_ids
        self.assertGreater(len(pids), 0)

    def test_patient_has_events(self):
        """Each patient has ECG events."""
        pid = self.dataset.unique_patient_ids[0]
        patient = self.dataset.get_patient(pid)
        events = patient.get_events()
        self.assertGreater(len(events), 0)

    def test_event_has_signal_file(self):
        """Events contain signal_file attribute."""
        pid = self.dataset.unique_patient_ids[0]
        patient = self.dataset.get_patient(pid)
        event = patient.get_events()[0]
        self.assertTrue(hasattr(event, "signal_file"))

    def test_event_has_lead(self):
        """Events contain lead attribute."""
        pid = self.dataset.unique_patient_ids[0]
        patient = self.dataset.get_patient(pid)
        event = patient.get_events()[0]
        self.assertTrue(hasattr(event, "lead"))


@unittest.skipUnless(HAS_TEST_DATA, "LUDB test data not found")
class TestLUDBHeaderParsing(unittest.TestCase):
    """Tests for LUDB patient metadata in wfdb headers."""

    def test_header_has_comments(self):
        """LUDB wfdb records contain header comments."""
        import wfdb

        data_dir = os.path.join(TEST_DATA_DIR, "data")
        rec = wfdb.rdrecord(os.path.join(data_dir, "1"))
        self.assertIsNotNone(rec.comments)
        self.assertGreater(len(rec.comments), 0)

    def test_header_has_age_sex(self):
        """Header comments contain age and sex fields."""
        import wfdb

        data_dir = os.path.join(TEST_DATA_DIR, "data")
        rec = wfdb.rdrecord(os.path.join(data_dir, "1"))
        comments = "\n".join(rec.comments)
        self.assertIn("<age>:", comments)
        self.assertIn("<sex>:", comments)

    def test_header_has_diagnoses(self):
        """Header comments contain diagnoses section."""
        import wfdb

        data_dir = os.path.join(TEST_DATA_DIR, "data")
        rec = wfdb.rdrecord(os.path.join(data_dir, "1"))
        comments = "\n".join(rec.comments)
        self.assertIn("<diagnoses>:", comments)


@unittest.skipUnless(HAS_TEST_DATA, "LUDB test data not found")
class TestECGWaveSegmentationTask(unittest.TestCase):
    """Tests for ECGWaveSegmentation with real LUDB data."""

    @classmethod
    def setUpClass(cls):
        from pyhealth.datasets.ludb import LUDBDataset
        from pyhealth.tasks.ecg_wave_segmentation import (
            ECGWaveSegmentation,
        )

        cls.dataset = LUDBDataset(root=TEST_DATA_DIR, dev=True)
        cls.task = ECGWaveSegmentation(window_size=512, step_size=256)

    def test_task_attributes(self):
        """Task has correct name and schema."""
        self.assertEqual(self.task.task_name, "ECGWaveSegmentation")
        self.assertEqual(self.task.input_schema, {"signal": "tensor"})
        self.assertEqual(self.task.output_schema, {"label": "tensor"})

    def test_task_produces_samples(self):
        """Task generates samples from a patient."""
        pid = self.dataset.unique_patient_ids[0]
        patient = self.dataset.get_patient(pid)
        samples = self.task(patient)
        self.assertGreater(len(samples), 0)

    def test_sample_has_required_keys(self):
        """Each sample has signal, label, patient_id."""
        pid = self.dataset.unique_patient_ids[0]
        patient = self.dataset.get_patient(pid)
        sample = self.task(patient)[0]
        self.assertIn("signal", sample)
        self.assertIn("label", sample)
        self.assertIn("patient_id", sample)

    def test_signal_shape(self):
        """Signal has shape (window_size,)."""
        pid = self.dataset.unique_patient_ids[0]
        patient = self.dataset.get_patient(pid)
        sample = self.task(patient)[0]
        self.assertEqual(sample["signal"].shape, (512,))

    def test_label_shape(self):
        """Label has shape (window_size,) matching signal."""
        pid = self.dataset.unique_patient_ids[0]
        patient = self.dataset.get_patient(pid)
        sample = self.task(patient)[0]
        self.assertEqual(sample["label"].shape, (512,))

    def test_labels_are_valid_classes(self):
        """Labels are 0 (bg), 1 (P), 2 (QRS), or 3 (T)."""
        pid = self.dataset.unique_patient_ids[0]
        patient = self.dataset.get_patient(pid)
        sample = self.task(patient)[0]
        unique = set(sample["label"].tolist())
        self.assertTrue(unique.issubset({0, 1, 2, 3}))

    def test_samples_contain_waves(self):
        """Default (no preprocess) produces samples containing wave labels."""
        pid = self.dataset.unique_patient_ids[0]
        patient = self.dataset.get_patient(pid)
        samples = self.task(patient)
        has_waves = any((s["label"] > 0).any() for s in samples)
        self.assertTrue(has_waves)

    def test_set_task_produces_sample_dataset(self):
        """dataset.set_task() returns a usable SampleDataset."""
        sample_ds = self.dataset.set_task(self.task)
        self.assertGreater(len(sample_ds), 0)
        sample = sample_ds[0]
        self.assertIn("signal", sample)
        self.assertIn("label", sample)


# ------------------------------------------------------------------ #
# Phase 2: patient-prompt plumbing (LUDB headers -> description)
# ------------------------------------------------------------------ #


def _force_regenerate_metadata():
    """Reset LUDB test state: delete committed CSV and PyHealth cache.

    The repo ships a pre-built ``ludb-pyhealth.csv`` and PyHealth
    caches the parsed event dataframe under ``~/.cache/pyhealth/``.
    Both need to be cleared so tests exercise the current
    ``prepare_metadata`` implementation and event schema from the
    YAML config, not stale artifacts from a prior run.
    """
    import shutil

    import platformdirs

    csv_path = os.path.join(TEST_DATA_DIR, "ludb-pyhealth.csv")
    if os.path.exists(csv_path):
        os.remove(csv_path)

    cache_root = platformdirs.user_cache_dir(appname="pyhealth")
    if os.path.isdir(cache_root):
        shutil.rmtree(cache_root)


@unittest.skipUnless(HAS_TEST_DATA, "LUDB test data not found")
class TestLUDBMetadataDemographics(unittest.TestCase):
    """Metadata CSV + events expose patient demographics."""

    @classmethod
    def setUpClass(cls):
        from pyhealth.datasets.ludb import LUDBDataset

        _force_regenerate_metadata()
        cls.dataset = LUDBDataset(root=TEST_DATA_DIR, dev=True)

    def test_metadata_csv_has_age_column(self):
        """Regenerated metadata CSV includes an ``age`` column."""
        import pandas as pd

        csv_path = os.path.join(TEST_DATA_DIR, "ludb-pyhealth.csv")
        df = pd.read_csv(csv_path)
        self.assertIn("age", df.columns)

    def test_metadata_csv_has_sex_column(self):
        """Regenerated metadata CSV includes a ``sex`` column."""
        import pandas as pd

        csv_path = os.path.join(TEST_DATA_DIR, "ludb-pyhealth.csv")
        df = pd.read_csv(csv_path)
        self.assertIn("sex", df.columns)

    def test_metadata_csv_has_diagnoses_column(self):
        """Regenerated metadata CSV includes a ``diagnoses`` column."""
        import pandas as pd

        csv_path = os.path.join(TEST_DATA_DIR, "ludb-pyhealth.csv")
        df = pd.read_csv(csv_path)
        self.assertIn("diagnoses", df.columns)

    def test_metadata_age_non_empty(self):
        """At least one row has a non-empty age."""
        import pandas as pd

        csv_path = os.path.join(TEST_DATA_DIR, "ludb-pyhealth.csv")
        df = pd.read_csv(csv_path)
        ages = df["age"].dropna().astype(str).str.strip()
        self.assertTrue((ages != "").any())

    def test_event_has_age_attr(self):
        """Events expose an ``age`` attribute."""
        pid = self.dataset.unique_patient_ids[0]
        patient = self.dataset.get_patient(pid)
        event = patient.get_events()[0]
        self.assertTrue(hasattr(event, "age"))

    def test_event_has_sex_attr(self):
        """Events expose a ``sex`` attribute."""
        pid = self.dataset.unique_patient_ids[0]
        patient = self.dataset.get_patient(pid)
        event = patient.get_events()[0]
        self.assertTrue(hasattr(event, "sex"))

    def test_event_has_diagnoses_attr(self):
        """Events expose a ``diagnoses`` attribute."""
        pid = self.dataset.unique_patient_ids[0]
        patient = self.dataset.get_patient(pid)
        event = patient.get_events()[0]
        self.assertTrue(hasattr(event, "diagnoses"))


@unittest.skipUnless(HAS_TEST_DATA, "LUDB test data not found")
class TestECGWaveSegmentationDescription(unittest.TestCase):
    """ECGWaveSegmentation emits per-sample ``description``."""

    @classmethod
    def setUpClass(cls):
        from pyhealth.datasets.ludb import LUDBDataset
        from pyhealth.tasks.ecg_wave_segmentation import (
            ECGWaveSegmentation,
        )

        _force_regenerate_metadata()
        cls.dataset = LUDBDataset(root=TEST_DATA_DIR, dev=True)
        cls.task = ECGWaveSegmentation(window_size=512, step_size=256)

    def test_sample_has_description_key(self):
        """Samples include a ``description`` field."""
        pid = self.dataset.unique_patient_ids[0]
        patient = self.dataset.get_patient(pid)
        sample = self.task(patient)[0]
        self.assertIn("description", sample)

    def test_description_is_string(self):
        """Description is a string."""
        pid = self.dataset.unique_patient_ids[0]
        patient = self.dataset.get_patient(pid)
        sample = self.task(patient)[0]
        self.assertIsInstance(sample["description"], str)

    def test_description_populated(self):
        """Description is non-empty for a patient with header data."""
        pid = self.dataset.unique_patient_ids[0]
        patient = self.dataset.get_patient(pid)
        sample = self.task(patient)[0]
        self.assertGreater(len(sample["description"]), 0)

    def test_description_contains_age(self):
        """Description mentions age for patient 1."""
        pid = self.dataset.unique_patient_ids[0]
        patient = self.dataset.get_patient(pid)
        sample = self.task(patient)[0]
        self.assertIn("age", sample["description"].lower())


@unittest.skipUnless(HAS_TEST_DATA, "LUDB test data not found")
class TestMedTsLLMWithLUDB(unittest.TestCase):
    """Test MedTsLLM model with real LUDB data structure."""

    @classmethod
    def setUpClass(cls):
        from pyhealth.datasets.ludb import LUDBDataset
        from pyhealth.tasks.ecg_wave_segmentation import (
            ECGWaveSegmentation,
        )
        from pyhealth.datasets import get_dataloader
        from pyhealth.models.medtsllm import MedTsLLM

        dataset = LUDBDataset(root=TEST_DATA_DIR, dev=True)
        task = ECGWaveSegmentation(window_size=128, step_size=64)
        cls.sample_ds = dataset.set_task(task)

        cls.model = MedTsLLM(
            dataset=cls.sample_ds,
            seq_len=128,
            n_features=1,
            n_classes=4,
            backbone=None,
            word_embeddings=torch.randn(50, 32),
            d_model=16,
            d_ff=32,
            n_heads=4,
            num_tokens=50,
        )
        loader = get_dataloader(cls.sample_ds, batch_size=2, shuffle=False)
        cls.batch = next(iter(loader))

    def test_forward(self):
        """Model forward pass works with real LUDB samples."""
        out = self.model(**self.batch)
        self.assertIn("logit", out)
        self.assertIn("loss", out)
        self.assertTrue(out["loss"].isfinite())

    def test_output_shape(self):
        """Output has correct shape for 4-class segmentation."""
        out = self.model(**self.batch)
        bs = self.batch["label"].shape[0]
        self.assertEqual(out["logit"].shape, (bs, 128, 4))


# ------------------------------------------------------------------ #
# Phase 5: paper-match split column (LUDB 80/20 seed=0)
# ------------------------------------------------------------------ #


@unittest.skipUnless(HAS_TEST_DATA, "LUDB test data not found")
class TestLUDBPaperSplit(unittest.TestCase):
    """paper_split=True writes an 80/20 seed=0 split column."""

    @classmethod
    def setUpClass(cls):
        from pyhealth.datasets.ludb import LUDBDataset

        _force_regenerate_metadata()
        cls.dataset = LUDBDataset(
            root=TEST_DATA_DIR, dev=True, paper_split=True
        )

    def test_constructor_accepts_paper_split(self):
        """LUDBDataset accepts a paper_split kwarg."""
        import inspect

        from pyhealth.datasets.ludb import LUDBDataset

        sig = inspect.signature(LUDBDataset.__init__)
        self.assertIn("paper_split", sig.parameters)

    def test_csv_has_split_column(self):
        """Regenerated CSV contains a ``split`` column."""
        import pandas as pd

        csv_path = os.path.join(TEST_DATA_DIR, "ludb-pyhealth.csv")
        df = pd.read_csv(csv_path)
        self.assertIn("split", df.columns)

    def test_split_values_are_train_or_test(self):
        """Every split value is either 'train' or 'test'."""
        import pandas as pd

        csv_path = os.path.join(TEST_DATA_DIR, "ludb-pyhealth.csv")
        df = pd.read_csv(csv_path)
        unique = set(df["split"].unique())
        self.assertTrue(unique.issubset({"train", "test"}))

    def test_split_consistent_per_patient(self):
        """Every lead of a patient shares one split assignment."""
        import pandas as pd

        csv_path = os.path.join(TEST_DATA_DIR, "ludb-pyhealth.csv")
        df = pd.read_csv(csv_path)
        for _, group in df.groupby("patient_id"):
            self.assertEqual(group["split"].nunique(), 1)

    def test_event_has_split_attr(self):
        """Events expose a ``split`` attribute."""
        pid = self.dataset.unique_patient_ids[0]
        patient = self.dataset.get_patient(pid)
        event = patient.get_events()[0]
        self.assertTrue(hasattr(event, "split"))
        self.assertIn(event.split, ("train", "test"))

    def test_task_emits_split_field(self):
        """ECGWaveSegmentation propagates event.split to each sample."""
        from pyhealth.tasks.ecg_wave_segmentation import (
            ECGWaveSegmentation,
        )

        pid = self.dataset.unique_patient_ids[0]
        patient = self.dataset.get_patient(pid)
        task = ECGWaveSegmentation(window_size=512, step_size=256)
        sample = task(patient)[0]
        self.assertIn("split", sample)
        self.assertIn(sample["split"], ("train", "test"))


@unittest.skipUnless(HAS_TEST_DATA, "LUDB test data not found")
class TestLUDBPaperSplitDeterministic(unittest.TestCase):
    """Seed=0 split is reproducible across runs."""

    def test_split_is_deterministic(self):
        """Regenerating twice yields the same patient -> split mapping."""
        import pandas as pd
        from pyhealth.datasets.ludb import LUDBDataset

        _force_regenerate_metadata()
        LUDBDataset(root=TEST_DATA_DIR, dev=True, paper_split=True)
        df1 = pd.read_csv(os.path.join(TEST_DATA_DIR, "ludb-pyhealth.csv"))
        mapping1 = df1.groupby("patient_id")["split"].first().to_dict()

        _force_regenerate_metadata()
        LUDBDataset(root=TEST_DATA_DIR, dev=True, paper_split=True)
        df2 = pd.read_csv(os.path.join(TEST_DATA_DIR, "ludb-pyhealth.csv"))
        mapping2 = df2.groupby("patient_id")["split"].first().to_dict()

        self.assertEqual(mapping1, mapping2)


@unittest.skipUnless(HAS_TEST_DATA, "LUDB test data not found")
class TestLUDBPaperSplitDisabled(unittest.TestCase):
    """paper_split=False does not assign train/test."""

    def test_split_column_blank_when_disabled(self):
        """Without paper_split, split column is empty."""
        import pandas as pd
        from pyhealth.datasets.ludb import LUDBDataset

        _force_regenerate_metadata()
        LUDBDataset(root=TEST_DATA_DIR, dev=True, paper_split=False)
        df = pd.read_csv(os.path.join(TEST_DATA_DIR, "ludb-pyhealth.csv"))
        self.assertIn("split", df.columns)
        cleaned = df["split"].fillna("").astype(str).str.strip()
        self.assertTrue((cleaned == "").all())


# ------------------------------------------------------------------ #
# Phase 6: preprocess=True -> .npz cache for LUDB
# ------------------------------------------------------------------ #


@unittest.skipUnless(HAS_TEST_DATA, "LUDB test data not found")
class TestLUDBPreprocessCache(unittest.TestCase):
    """preprocess=True writes .npz per (patient, lead) and wires events."""

    @classmethod
    def setUpClass(cls):
        import shutil

        from pyhealth.datasets.ludb import LUDBDataset

        # Clear any prior run's cache so paths/fingerprints are fresh.
        processed_dir = os.path.join(TEST_DATA_DIR, "processed")
        if os.path.isdir(processed_dir):
            shutil.rmtree(processed_dir)
        _force_regenerate_metadata()

        cls.dataset = LUDBDataset(
            root=TEST_DATA_DIR, dev=True, preprocess=True
        )

    def test_processed_dir_created(self):
        """preprocess=True creates {root}/processed/."""
        self.assertTrue(
            os.path.isdir(os.path.join(TEST_DATA_DIR, "processed"))
        )

    def test_npz_written_per_lead(self):
        """Every (record, lead) pair has a corresponding .npz."""
        processed_dir = os.path.join(TEST_DATA_DIR, "processed")
        files = os.listdir(processed_dir)
        npz_files = [f for f in files if f.endswith(".npz")]
        # 2 records * 12 leads = 24 expected
        self.assertGreaterEqual(len(npz_files), 20)

    def test_event_has_processed_file_attr(self):
        """Events expose the cache path via ``processed_file``."""
        pid = self.dataset.unique_patient_ids[0]
        patient = self.dataset.get_patient(pid)
        event = patient.get_events()[0]
        self.assertTrue(hasattr(event, "processed_file"))
        self.assertTrue(event.processed_file.endswith(".npz"))
        self.assertTrue(os.path.exists(event.processed_file))

    def test_cached_arrays_have_expected_keys(self):
        """Each .npz stores signal + labels arrays."""
        pid = self.dataset.unique_patient_ids[0]
        patient = self.dataset.get_patient(pid)
        event = patient.get_events()[0]
        with np.load(event.processed_file, allow_pickle=False) as npz:
            self.assertIn("signal", npz.files)
            self.assertIn("labels", npz.files)
            self.assertEqual(npz["signal"].shape, npz["labels"].shape)

    def test_cached_labels_contain_waves(self):
        """Cached labels include non-background classes after trim."""
        pid = self.dataset.unique_patient_ids[0]
        patient = self.dataset.get_patient(pid)
        event = patient.get_events()[0]
        with np.load(event.processed_file, allow_pickle=False) as npz:
            self.assertTrue((npz["labels"] > 0).any())

    def test_task_loads_from_cache(self):
        """ECGWaveSegmentation returns samples using cached arrays."""
        from pyhealth.tasks.ecg_wave_segmentation import (
            ECGWaveSegmentation,
        )

        pid = self.dataset.unique_patient_ids[0]
        patient = self.dataset.get_patient(pid)
        task = ECGWaveSegmentation(window_size=128, step_size=64)
        samples = task(patient)
        self.assertGreater(len(samples), 0)
        self.assertEqual(samples[0]["signal"].shape, (128,))


@unittest.skipUnless(HAS_TEST_DATA, "LUDB test data not found")
class TestLUDBPreprocessDisabled(unittest.TestCase):
    """preprocess=False leaves processed_file blank."""

    def test_processed_file_empty_when_disabled(self):
        import shutil

        from pyhealth.datasets.ludb import LUDBDataset

        processed_dir = os.path.join(TEST_DATA_DIR, "processed")
        if os.path.isdir(processed_dir):
            shutil.rmtree(processed_dir)
        _force_regenerate_metadata()

        ds = LUDBDataset(root=TEST_DATA_DIR, dev=True, preprocess=False)
        pid = ds.unique_patient_ids[0]
        event = ds.get_patient(pid).get_events()[0]
        value = getattr(event, "processed_file", "") or ""
        self.assertEqual(str(value).strip(), "")


@unittest.skipUnless(HAS_TEST_DATA, "LUDB test data not found")
class TestLUDBPreprocessTrimOff(unittest.TestCase):
    """preprocess=True, trim=False caches the full (untrimmed) lead."""

    def test_untrimmed_cache_is_longer(self):
        import shutil

        from pyhealth.datasets.ludb import LUDBDataset

        processed_dir = os.path.join(TEST_DATA_DIR, "processed")

        # Build trimmed cache first.
        if os.path.isdir(processed_dir):
            shutil.rmtree(processed_dir)
        _force_regenerate_metadata()
        ds_trim = LUDBDataset(
            root=TEST_DATA_DIR, dev=True, preprocess=True, trim=True
        )
        pid_trim = ds_trim.unique_patient_ids[0]
        ev_trim = ds_trim.get_patient(pid_trim).get_events()[0]
        with np.load(ev_trim.processed_file, allow_pickle=False) as npz:
            trimmed_len = int(npz["signal"].shape[0])

        # Rebuild with trim=False.
        if os.path.isdir(processed_dir):
            shutil.rmtree(processed_dir)
        _force_regenerate_metadata()
        ds_full = LUDBDataset(
            root=TEST_DATA_DIR, dev=True, preprocess=True, trim=False
        )
        pid_full = ds_full.unique_patient_ids[0]
        ev_full = ds_full.get_patient(pid_full).get_events()[0]
        with np.load(ev_full.processed_file, allow_pickle=False) as npz:
            full_len = int(npz["signal"].shape[0])

        self.assertGreaterEqual(full_len, trimmed_len)


if __name__ == "__main__":
    unittest.main()
