"""Unit tests for BIDMC dataset and RespiratoryBoundaryDetection task.

Author: Anton Barchukov

Tests cover:
    - BIDMCDataset instantiation from wfdb files
    - Metadata preparation
    - Patient header parsing (age, sex, location)
    - RespiratoryBoundaryDetection task (windowing, annotator, labels)
    - Full pipeline: dataset -> task -> samples
    - MedTsLLM model with the BIDMC data structure

Test data under ``test-resources/core/bidmc/`` is fully synthetic —
records generated by ``tests/core/_synthetic_wfdb.synthesize_bidmc``
with placeholder respiratory/ECG signals. No real patient records
are committed to the repo.
"""

import os
import unittest

import numpy as np
import torch

TEST_DATA_DIR = os.path.join(
    os.path.dirname(__file__), "..", "..", "test-resources", "core", "bidmc"
)
HAS_TEST_DATA = os.path.isdir(TEST_DATA_DIR) and any(
    f.endswith(".dat") for f in os.listdir(TEST_DATA_DIR)
)


def setUpModule():
    """Drop the committed CSV + cache so tests use the current schema."""
    if HAS_TEST_DATA:
        _force_regenerate_bidmc_metadata()


@unittest.skipUnless(HAS_TEST_DATA, "BIDMC test data not found")
class TestBIDMCDataset(unittest.TestCase):
    """Tests for BIDMCDataset with real wfdb files."""

    @classmethod
    def setUpClass(cls):
        from pyhealth.datasets.bidmc import BIDMCDataset

        cls.dataset = BIDMCDataset(root=TEST_DATA_DIR, dev=True)

    def test_dataset_loads(self):
        """Dataset initializes without error."""
        self.assertIsNotNone(self.dataset)

    def test_metadata_csv_created(self):
        """prepare_metadata creates bidmc-pyhealth.csv."""
        csv_path = os.path.join(TEST_DATA_DIR, "bidmc-pyhealth.csv")
        self.assertTrue(os.path.exists(csv_path))

    def test_has_patients(self):
        """Dataset has at least 1 patient."""
        pids = self.dataset.unique_patient_ids
        self.assertGreater(len(pids), 0)

    def test_patient_has_events(self):
        """Each patient has respiratory events."""
        pid = self.dataset.unique_patient_ids[0]
        patient = self.dataset.get_patient(pid)
        events = patient.get_events()
        self.assertGreater(len(events), 0)

    def test_event_has_demographics(self):
        """Events contain age and sex attributes."""
        pid = self.dataset.unique_patient_ids[0]
        patient = self.dataset.get_patient(pid)
        event = patient.get_events()[0]
        self.assertTrue(hasattr(event, "age"))
        self.assertTrue(hasattr(event, "sex"))
        self.assertTrue(hasattr(event, "location"))


@unittest.skipUnless(HAS_TEST_DATA, "BIDMC test data not found")
class TestBIDMCHeaderParsing(unittest.TestCase):
    """Tests for BIDMC patient metadata parsing."""

    def test_parse_header(self):
        """Header parsing extracts age, sex, location."""
        import wfdb

        rec = wfdb.rdrecord(os.path.join(TEST_DATA_DIR, "bidmc01"))
        from pyhealth.datasets.bidmc import BIDMCDataset

        # Just verify the record has comments
        self.assertIsNotNone(rec.comments)
        self.assertGreater(len(rec.comments), 0)


@unittest.skipUnless(HAS_TEST_DATA, "BIDMC test data not found")
class TestRespiratoryBoundaryDetectionTask(unittest.TestCase):
    """Tests for RespiratoryBoundaryDetection with real data."""

    @classmethod
    def setUpClass(cls):
        from pyhealth.datasets.bidmc import BIDMCDataset
        from pyhealth.tasks.respiratory_boundary_detection import (
            RespiratoryBoundaryDetection,
        )

        cls.dataset = BIDMCDataset(root=TEST_DATA_DIR, dev=True)
        cls.task = RespiratoryBoundaryDetection(
            window_size=256, step_size=128
        )

    def test_task_attributes(self):
        """Task has correct name and schema."""
        self.assertEqual(
            self.task.task_name, "RespiratoryBoundaryDetection"
        )
        self.assertEqual(self.task.input_schema, {"signal": "tensor"})
        self.assertEqual(self.task.output_schema, {"label": "tensor"})

    def test_task_produces_samples(self):
        """Task generates samples from a patient."""
        pid = self.dataset.unique_patient_ids[0]
        patient = self.dataset.get_patient(pid)
        samples = self.task(patient)
        self.assertGreater(len(samples), 0)

    def test_signal_is_3_channel(self):
        """Signal has 3 channels (RESP, PLETH, II)."""
        pid = self.dataset.unique_patient_ids[0]
        patient = self.dataset.get_patient(pid)
        sample = self.task(patient)[0]
        self.assertEqual(sample["signal"].shape, (256, 3))

    def test_label_is_binary(self):
        """Labels are 0 or 1 (boundary or not)."""
        pid = self.dataset.unique_patient_ids[0]
        patient = self.dataset.get_patient(pid)
        sample = self.task(patient)[0]
        unique = set(sample["label"].tolist())
        self.assertTrue(unique.issubset({0.0, 1.0}))

    def test_sample_has_description(self):
        """Samples include patient description."""
        pid = self.dataset.unique_patient_ids[0]
        patient = self.dataset.get_patient(pid)
        sample = self.task(patient)[0]
        self.assertIn("description", sample)
        self.assertIn("age:", sample["description"])

    def test_set_task_produces_sample_dataset(self):
        """dataset.set_task() returns a usable SampleDataset."""
        sample_ds = self.dataset.set_task(self.task)
        self.assertGreater(len(sample_ds), 0)


@unittest.skipUnless(HAS_TEST_DATA, "BIDMC test data not found")
class TestMedTsLLMWithBIDMC(unittest.TestCase):
    """Test MedTsLLM model with real BIDMC data structure."""

    @classmethod
    def setUpClass(cls):
        from pyhealth.datasets.bidmc import BIDMCDataset
        from pyhealth.tasks.respiratory_boundary_detection import (
            RespiratoryBoundaryDetection,
        )
        from pyhealth.datasets import get_dataloader
        from pyhealth.models.medtsllm import MedTsLLM

        dataset = BIDMCDataset(root=TEST_DATA_DIR, dev=True)
        task = RespiratoryBoundaryDetection(
            window_size=128, step_size=64
        )
        cls.sample_ds = dataset.set_task(task)

        cls.model = MedTsLLM(
            dataset=cls.sample_ds,
            seq_len=128,
            n_features=3,
            n_classes=2,
            backbone=None,
            word_embeddings=torch.randn(50, 32),
            d_model=16,
            d_ff=32,
            n_heads=4,
            num_tokens=50,
            covariate_mode="concat",
        )
        loader = get_dataloader(cls.sample_ds, batch_size=2, shuffle=False)
        cls.batch = next(iter(loader))

    def test_forward(self):
        """Model forward pass works with real BIDMC samples."""
        out = self.model(**self.batch)
        self.assertIn("logit", out)
        self.assertIn("loss", out)
        self.assertTrue(out["loss"].isfinite())

    def test_backward(self):
        """Backward pass works with BIDMC data."""
        out = self.model(**self.batch)
        out["loss"].backward()


# ------------------------------------------------------------------ #
# Phase 5: paper-match split column (BIDMC 85/15 seed=0)
# ------------------------------------------------------------------ #


def _force_regenerate_bidmc_metadata():
    """Reset BIDMC test state: delete CSV and PyHealth cache."""
    import shutil

    import platformdirs

    csv_path = os.path.join(TEST_DATA_DIR, "bidmc-pyhealth.csv")
    if os.path.exists(csv_path):
        os.remove(csv_path)

    cache_root = platformdirs.user_cache_dir(appname="pyhealth")
    if os.path.isdir(cache_root):
        shutil.rmtree(cache_root)


@unittest.skipUnless(HAS_TEST_DATA, "BIDMC test data not found")
class TestBIDMCPaperSplit(unittest.TestCase):
    """paper_split=True writes an 85/15 seed=0 split column."""

    @classmethod
    def setUpClass(cls):
        from pyhealth.datasets.bidmc import BIDMCDataset

        _force_regenerate_bidmc_metadata()
        cls.dataset = BIDMCDataset(
            root=TEST_DATA_DIR, dev=True, paper_split=True
        )

    def test_constructor_accepts_paper_split(self):
        """BIDMCDataset accepts a paper_split kwarg."""
        import inspect

        from pyhealth.datasets.bidmc import BIDMCDataset

        sig = inspect.signature(BIDMCDataset.__init__)
        self.assertIn("paper_split", sig.parameters)

    def test_csv_has_split_column(self):
        """Regenerated CSV contains a ``split`` column."""
        import pandas as pd

        csv_path = os.path.join(TEST_DATA_DIR, "bidmc-pyhealth.csv")
        df = pd.read_csv(csv_path)
        self.assertIn("split", df.columns)

    def test_split_values_are_train_or_test(self):
        """Every split value is either 'train' or 'test'."""
        import pandas as pd

        csv_path = os.path.join(TEST_DATA_DIR, "bidmc-pyhealth.csv")
        df = pd.read_csv(csv_path)
        unique = set(df["split"].unique())
        self.assertTrue(unique.issubset({"train", "test"}))

    def test_event_has_split_attr(self):
        """Events expose a ``split`` attribute."""
        pid = self.dataset.unique_patient_ids[0]
        patient = self.dataset.get_patient(pid)
        event = patient.get_events()[0]
        self.assertTrue(hasattr(event, "split"))
        self.assertIn(event.split, ("train", "test"))

    def test_task_emits_split_field(self):
        """RespiratoryBoundaryDetection propagates event.split to samples."""
        from pyhealth.tasks.respiratory_boundary_detection import (
            RespiratoryBoundaryDetection,
        )

        pid = self.dataset.unique_patient_ids[0]
        patient = self.dataset.get_patient(pid)
        task = RespiratoryBoundaryDetection(
            window_size=256, step_size=128
        )
        sample = task(patient)[0]
        self.assertIn("split", sample)
        self.assertIn(sample["split"], ("train", "test"))


@unittest.skipUnless(HAS_TEST_DATA, "BIDMC test data not found")
class TestBIDMCPaperSplitDeterministic(unittest.TestCase):
    """Seed=0 BIDMC split is reproducible across runs."""

    def test_split_is_deterministic(self):
        """Regenerating twice yields the same patient -> split mapping."""
        import pandas as pd
        from pyhealth.datasets.bidmc import BIDMCDataset

        _force_regenerate_bidmc_metadata()
        BIDMCDataset(root=TEST_DATA_DIR, dev=True, paper_split=True)
        df1 = pd.read_csv(os.path.join(TEST_DATA_DIR, "bidmc-pyhealth.csv"))
        mapping1 = df1.set_index("patient_id")["split"].to_dict()

        _force_regenerate_bidmc_metadata()
        BIDMCDataset(root=TEST_DATA_DIR, dev=True, paper_split=True)
        df2 = pd.read_csv(os.path.join(TEST_DATA_DIR, "bidmc-pyhealth.csv"))
        mapping2 = df2.set_index("patient_id")["split"].to_dict()

        self.assertEqual(mapping1, mapping2)


@unittest.skipUnless(HAS_TEST_DATA, "BIDMC test data not found")
class TestBIDMCPaperSplitDisabled(unittest.TestCase):
    """paper_split=False leaves the split column blank."""

    def test_split_column_blank_when_disabled(self):
        """Without paper_split, split column is empty."""
        import pandas as pd
        from pyhealth.datasets.bidmc import BIDMCDataset

        _force_regenerate_bidmc_metadata()
        BIDMCDataset(root=TEST_DATA_DIR, dev=True, paper_split=False)
        df = pd.read_csv(os.path.join(TEST_DATA_DIR, "bidmc-pyhealth.csv"))
        self.assertIn("split", df.columns)
        cleaned = df["split"].fillna("").astype(str).str.strip()
        self.assertTrue((cleaned == "").all())


# ------------------------------------------------------------------ #
# Phase 6: preprocess=True -> .npz cache for BIDMC
# ------------------------------------------------------------------ #


@unittest.skipUnless(HAS_TEST_DATA, "BIDMC test data not found")
class TestBIDMCPreprocessCache(unittest.TestCase):
    """preprocess=True writes per-record .npz with signal + annotations."""

    @classmethod
    def setUpClass(cls):
        import shutil

        from pyhealth.datasets.bidmc import BIDMCDataset

        processed_dir = os.path.join(TEST_DATA_DIR, "processed")
        if os.path.isdir(processed_dir):
            shutil.rmtree(processed_dir)
        _force_regenerate_bidmc_metadata()

        cls.dataset = BIDMCDataset(
            root=TEST_DATA_DIR, dev=True, preprocess=True
        )

    def test_processed_dir_created(self):
        self.assertTrue(
            os.path.isdir(os.path.join(TEST_DATA_DIR, "processed"))
        )

    def test_event_has_processed_file_attr(self):
        pid = self.dataset.unique_patient_ids[0]
        event = self.dataset.get_patient(pid).get_events()[0]
        self.assertTrue(hasattr(event, "processed_file"))
        self.assertTrue(event.processed_file.endswith(".npz"))
        self.assertTrue(os.path.exists(event.processed_file))

    def test_cached_arrays_have_expected_keys(self):
        pid = self.dataset.unique_patient_ids[0]
        event = self.dataset.get_patient(pid).get_events()[0]
        with np.load(event.processed_file, allow_pickle=False) as npz:
            self.assertIn("signal", npz.files)
            self.assertIn("ann_sample", npz.files)
            self.assertIn("ann_aux", npz.files)

    def test_cached_signal_is_3_channel(self):
        pid = self.dataset.unique_patient_ids[0]
        event = self.dataset.get_patient(pid).get_events()[0]
        with np.load(event.processed_file, allow_pickle=False) as npz:
            self.assertEqual(int(npz["signal"].shape[1]), 3)

    def test_task_uses_cache(self):
        from pyhealth.tasks.respiratory_boundary_detection import (
            RespiratoryBoundaryDetection,
        )

        pid = self.dataset.unique_patient_ids[0]
        patient = self.dataset.get_patient(pid)
        samples = RespiratoryBoundaryDetection(
            window_size=256, step_size=128
        )(patient)
        self.assertGreater(len(samples), 0)
        self.assertEqual(samples[0]["signal"].shape, (256, 3))


@unittest.skipUnless(HAS_TEST_DATA, "BIDMC test data not found")
class TestBIDMCPreprocessDisabled(unittest.TestCase):
    """preprocess=False leaves processed_file blank."""

    def test_processed_file_empty_when_disabled(self):
        import shutil

        from pyhealth.datasets.bidmc import BIDMCDataset

        processed_dir = os.path.join(TEST_DATA_DIR, "processed")
        if os.path.isdir(processed_dir):
            shutil.rmtree(processed_dir)
        _force_regenerate_bidmc_metadata()

        ds = BIDMCDataset(root=TEST_DATA_DIR, dev=True, preprocess=False)
        pid = ds.unique_patient_ids[0]
        event = ds.get_patient(pid).get_events()[0]
        value = getattr(event, "processed_file", "") or ""
        self.assertEqual(str(value).strip(), "")


if __name__ == "__main__":
    unittest.main()
