-- THIS SCRIPT IS AUTOMATICALLY GENERATED. DO NOT EDIT IT DIRECTLY.
DROP TABLE IF EXISTS ventilation_first_day;
CREATE TABLE ventilation_first_day AS
-- Determines if a patient is ventilated on the first day of their ICU stay.
-- Creates a table with the result.
-- Requires the `ventilation_durations` table, generated by ../ventilation-durations.sql

SELECT
  ie.subject_id, ie.hadm_id, ie.icustay_id
  -- if vd.icustay_id is not null, then they have a valid ventilation event
  -- matching the time criteria in the JOIN condition.
  -- In this case, we say they are ventilated (1).
  -- Otherwise, they are not (0). MAX() ensures we get 1 if any matching record exists.
  , MAX(CASE
      WHEN vd.icustay_id IS NOT NULL THEN 1
      ELSE 0 END) AS vent
FROM icustays ie -- Assuming icustays table exists
LEFT JOIN ventilation_durations vd -- Assuming ventilation_durations table exists
  ON ie.icustay_id = vd.icustay_id
  AND
  (
    -- Ventilation duration overlaps with ICU admission -> vented on admission
    (vd.starttime <= ie.intime AND vd.endtime >= ie.intime)
    -- Ventilation started during the first day (within 24 hours of intime)
    -- Replace DATETIME_ADD with PostgreSQL interval addition
    OR (vd.starttime >= ie.intime AND vd.starttime <= (ie.intime + INTERVAL '1 day'))
  )
GROUP BY ie.subject_id, ie.hadm_id, ie.icustay_id
ORDER BY ie.subject_id, ie.hadm_id, ie.icustay_id;