version: "5.0"
tables:
  amiodarone_trials:
    file_path: "amiodarone_trials-metadata-pyhealth.csv"
    patient_id: "patient_id"
    timestamp: null
    attributes:
    - "visit_id"
    - "trial_name"
    - "amiodarone_total_24h_mg"
    - "comparison_intensity"
    - "af_duration_gt_48h"
    - "outcome_time_gt_48h"
    - "mean_age"
    - "mean_la_size"
    - "fraction_male"
    - "fraction_cv_disease"
    - "followup_fraction"
    - "adequate_concealment"
    - "masked_patients"
    - "masked_caregiver"
    - "masked_assessor"
    - "log_relative_risk"
    - "variance"
    - "split"