# Author: Sezim Zamirbekova (szami2) and Niam Pattni (npattni2)
version: "1.0"
tables:
  daily_sport_activities:
    file_path: ""
    patient_id: "patient_id"
    timestamp: null
    attributes:
    - "record_id"
    - "patient_id"
    - "visit_id"
    - "activity_id"
    - "activity"
    - "segment"
    - "file_path"
    - "signal"