# DREAMS Dataset Final Features Configuration
version: "1.0"
tables:
  dreamt_features:
    file_path: "all_patients_domain_features.csv"
    patient_id: "sid"
    timestamp: "timestamp_start"
    attributes:
      # Core Features
      - "PPG_Rate_Mean"
      - "HRV_SDNN"
      - "HRV_MadNN"
      - "HRV_SDRMSSD"
      - "HRV_Prc20NN"
      - "HRV_Prc80NN"
      - "HRV_pNN50"
      - "HRV_MinNN"
      - "HRV_MaxNN"
      - "HRV_HTI"
      - "HRV_TINN"
      - "HRV_HF"
      - "HRV_VHF"
      - "HRV_HFn"
      - "HRV_SD1SD2"
      - "HRV_S"
      - "HRV_CVI"
      - "HRV_CSI_Modified"
      - "HRV_PIP"
      - "HRV_IALS"
      - "HRV_PSS"
      - "HRV_PAS"
      - "HRV_GI"
      - "HRV_PI"
      - "HRV_C1d"
      - "HRV_C2d"
      - "HRV_Cd_MIXED"
      - "HRV_DFA_alpha1"
      - "HRV_MFDFA_alpha1_Width"
      - "HRV_MFDFA_alpha1_Peak"
      - "HRV_MFDFA_alpha1_Mean"
      - "HRV_MFDFA_alpha1_Max"
      - "HRV_MFDFA_alpha1_Delta"
      - "HRV_MFDFA_alpha1_Asymmetry"
      - "HRV_MFDFA_alpha1_Fluctuation"
      - "HRV_ApEn"
      - "HRV_ShanEn"
      - "HRV_FuzzyEn"
      - "HRV_CD_UPPER"
      - "HRV_HFD"
      - "HRV_KFD"
      - "HRV_LZC"
      - "total_power"
      - "normalized_power"
      - "HF_frequency_power"
      - "LF_frequency_peak"
      - "HF_frequency_peak"
      - "HR_mean"
      - "HR_max"
      - "HR_min"
      - "BVP_mean"
      - "BVP_median"
      - "BVP_max"
      - "BVP_std"
      - "ACC_X_trimmed_mean"
      - "ACC_X_trimmed_max"
      - "ACC_Y_trimmed_mean"
      - "ACC_Z_trimmed_mean"
      - "ACC_X_MAD_trimmed_IQR"
      - "ACC_INDEX"
      - "TEMP_mean"
      - "TEMP_std"
      - "mean_SCR_Height"
      - "mean_SCR_RiseTime"
      - "max_SCR_RiseTime"
      - "mean_SCR_RecoveryTime"
      - "max_SCR_RecoveryTime"
      
      # Rolling Variance Features
      - "rolling_var_PPG_Rate_Mean"
      - "rolling_var_HRV_MeanNN"
      - "rolling_var_HRV_SDNN"
      - "rolling_var_HRV_CVNN"
      - "rolling_var_HRV_MedianNN"
      - "rolling_var_HRV_MadNN"
      - "rolling_var_HRV_IQRNN"
      - "rolling_var_HRV_SDRMSSD"
      - "rolling_var_HRV_Prc20NN"
      - "rolling_var_HRV_Prc80NN"
      - "rolling_var_HRV_pNN50"
      - "rolling_var_HRV_pNN20"
      - "rolling_var_HRV_MinNN"
      - "rolling_var_HRV_HTI"
      - "rolling_var_HRV_TINN"
      - "rolling_var_HRV_HF"
      - "rolling_var_HRV_VHF"
      - "rolling_var_HRV_HFn"
      - "rolling_var_HRV_LnHF"
      - "rolling_var_HRV_SD1SD2"
      - "rolling_var_HRV_S"
      - "rolling_var_HRV_CVI"
      - "rolling_var_HRV_CSI_Modified"
      - "rolling_var_HRV_PIP"
      - "rolling_var_HRV_IALS"
      - "rolling_var_HRV_PSS"
      - "rolling_var_HRV_PAS"
      - "rolling_var_HRV_GI"
      - "rolling_var_HRV_PI"
      - "rolling_var_HRV_C1d"
      - "rolling_var_HRV_C2d"
      - "rolling_var_HRV_Cd_MIXED"
      - "rolling_var_HRV_DFA_alpha1"
      - "rolling_var_HRV_MFDFA_alpha1_Width"
      - "rolling_var_HRV_MFDFA_alpha1_Peak"
      - "rolling_var_HRV_MFDFA_alpha1_Mean"
      - "rolling_var_HRV_MFDFA_alpha1_Max"
      - "rolling_var_HRV_MFDFA_alpha1_Delta"
      - "rolling_var_HRV_MFDFA_alpha1_Asymmetry"
      - "rolling_var_HRV_MFDFA_alpha1_Fluctuation"
      - "rolling_var_HRV_ApEn"
      - "rolling_var_HRV_SampEn"
      - "rolling_var_HRV_ShanEn"
      - "rolling_var_HRV_FuzzyEn"
      - "rolling_var_HRV_CD_UPPER"
      - "rolling_var_HRV_HFD"
      - "rolling_var_HRV_KFD"
      - "rolling_var_HRV_LZC"
      - "rolling_var_total_power"
      - "rolling_var_normalized_power"
      - "rolling_var_HF_frequency_power"
      - "rolling_var_LF_frequency_peak"
      - "rolling_var_HF_frequency_peak"
      - "rolling_var_HR_mean"
      - "rolling_var_HR_median"
      - "rolling_var_HR_max"
      - "rolling_var_HR_min"
      - "rolling_var_HR_std"
      - "rolling_var_BVP_mean"
      - "rolling_var_BVP_median"
      - "rolling_var_BVP_max"
      - "rolling_var_BVP_min"
      - "rolling_var_BVP_std"
      - "rolling_var_ACC_X_trimmed_mean"
      - "rolling_var_ACC_X_trimmed_max"
      - "rolling_var_ACC_X_trimmed_IQR"
      - "rolling_var_ACC_Y_trimmed_mean"
      - "rolling_var_ACC_Y_trimmed_max"
      - "rolling_var_ACC_Z_trimmed_mean"
      - "rolling_var_ACC_X_MAD_trimmed_max"
      - "rolling_var_ACC_X_MAD_trimmed_IQR"
      - "rolling_var_ACC_Y_MAD_trimmed_max"
      - "rolling_var_ACC_Y_MAD_trimmed_IQR"
      - "rolling_var_ACC_Z_MAD_trimmed_max"
      - "rolling_var_ACC_Z_MAD_trimmed_IQR"
      - "rolling_var_TEMP_mean"
      - "rolling_var_TEMP_std"
      - "rolling_var_mean_SCR_Height"
      - "rolling_var_mean_SCR_RiseTime"
      - "rolling_var_max_SCR_RiseTime"
      - "rolling_var_mean_SCR_RecoveryTime"
      - "rolling_var_max_SCR_RecoveryTime"
      
      # Gaussian Features
      - "gaussian_PPG_Rate_Mean"
      - "gaussian_HRV_MeanNN"
      - "gaussian_HRV_SDNN"
      - "gaussian_HRV_SDRMSSD"
      - "gaussian_HRV_Prc20NN"
      - "gaussian_HRV_Prc80NN"
      - "gaussian_HRV_pNN50"
      - "gaussian_HRV_MinNN"
      - "gaussian_HRV_TINN"
      - "gaussian_HRV_HF"
      - "gaussian_HRV_VHF"
      - "gaussian_HRV_HFn"
      - "gaussian_HRV_SD1SD2"
      - "gaussian_HRV_S"
      - "gaussian_HRV_PIP"
      - "gaussian_HRV_PSS"
      - "gaussian_HRV_GI"
      - "gaussian_HRV_PI"
      - "gaussian_HRV_C1d"
      - "gaussian_HRV_C1a"
      - "gaussian_HRV_C2d"
      - "gaussian_HRV_C2a"
      - "gaussian_HRV_Cd"
      - "gaussian_HRV_Ca"
      - "gaussian_HRV_DFA_alpha1"
      - "gaussian_HRV_MFDFA_alpha1_Width"
      - "gaussian_HRV_MFDFA_alpha1_Peak"
      - "gaussian_HRV_MFDFA_alpha1_Mean"
      - "gaussian_HRV_MFDFA_alpha1_Max"
      - "gaussian_HRV_MFDFA_alpha1_Delta"
      - "gaussian_HRV_MFDFA_alpha1_Asymmetry"
      - "gaussian_HRV_MFDFA_alpha1_Fluctuation"
      - "gaussian_HRV_ApEn"
      - "gaussian_HRV_FuzzyEn"
      - "gaussian_HRV_HFD"
      - "gaussian_HRV_KFD"
      - "gaussian_HRV_LZC"
      - "gaussian_total_power"
      - "gaussian_normalized_power"
      - "gaussian_HF_frequency_power"
      - "gaussian_LF_frequency_peak"
      - "gaussian_HF_frequency_peak"
      - "gaussian_HR_mean"
      - "gaussian_HR_max"
      - "gaussian_HR_min"
      - "gaussian_BVP_mean"
      - "gaussian_BVP_max"
      - "gaussian_BVP_std"
      - "gaussian_ACC_X_trimmed_mean"
      - "gaussian_ACC_X_trimmed_max"
      - "gaussian_ACC_Y_trimmed_mean"
      - "gaussian_ACC_Z_trimmed_mean"
      - "gaussian_TEMP_mean"
      - "gaussian_TEMP_std"
      - "gaussian_mean_SCR_Height"
      - "gaussian_mean_SCR_RiseTime"
      - "gaussian_max_SCR_RiseTime"
      - "gaussian_mean_SCR_RecoveryTime"
      - "gaussian_max_SCR_RecoveryTime"
      
      # First Derivative Features
      - "gaussian_PPG_Rate_Mean_1st_derivative"
      - "raw_PPG_Rate_Mean_1st_derivative"
      - "gaussian_HRV_MeanNN_1st_derivative"
      - "gaussian_HRV_SDNN_1st_derivative"
      - "raw_HRV_SDNN_1st_derivative"
      - "raw_HRV_MedianNN_1st_derivative"
      - "gaussian_HRV_MadNN_1st_derivative"
      - "raw_HRV_MadNN_1st_derivative"
      - "raw_HRV_IQRNN_1st_derivative"
      - "gaussian_HRV_SDRMSSD_1st_derivative"
      - "raw_HRV_SDRMSSD_1st_derivative"
      - "gaussian_HRV_Prc20NN_1st_derivative"
      - "raw_HRV_Prc20NN_1st_derivative"
      - "gaussian_HRV_Prc80NN_1st_derivative"
      - "raw_HRV_Prc80NN_1st_derivative"
      - "gaussian_HRV_pNN50_1st_derivative"
      - "raw_HRV_pNN50_1st_derivative"
      - "gaussian_HRV_pNN20_1st_derivative"
      - "raw_HRV_pNN20_1st_derivative"
      - "gaussian_HRV_MinNN_1st_derivative"
      - "raw_HRV_MinNN_1st_derivative"
      - "gaussian_HRV_MaxNN_1st_derivative"
      - "raw_HRV_MaxNN_1st_derivative"
      - "gaussian_HRV_HTI_1st_derivative"
      - "raw_HRV_HTI_1st_derivative"
      - "gaussian_HRV_TINN_1st_derivative"
      - "raw_HRV_TINN_1st_derivative"
      - "gaussian_HRV_HF_1st_derivative"
      - "raw_HRV_HF_1st_derivative"
      - "gaussian_HRV_VHF_1st_derivative"
      - "raw_HRV_VHF_1st_derivative"
      - "gaussian_HRV_HFn_1st_derivative"
      - "raw_HRV_HFn_1st_derivative"
      - "gaussian_HRV_LnHF_1st_derivative"
      - "raw_HRV_LnHF_1st_derivative"
      - "gaussian_HRV_SD1SD2_1st_derivative"
      - "raw_HRV_SD1SD2_1st_derivative"
      - "gaussian_HRV_S_1st_derivative"
      - "raw_HRV_S_1st_derivative"
      - "gaussian_HRV_CVI_1st_derivative"
      - "raw_HRV_CVI_1st_derivative"
      - "gaussian_HRV_CSI_Modified_1st_derivative"
      - "raw_HRV_CSI_Modified_1st_derivative"
      - "gaussian_HRV_PIP_1st_derivative"
      - "raw_HRV_PIP_1st_derivative"
      - "raw_HRV_IALS_1st_derivative"
      - "gaussian_HRV_PSS_1st_derivative"
      - "raw_HRV_PSS_1st_derivative"
      - "gaussian_HRV_PAS_1st_derivative"
      - "raw_HRV_PAS_1st_derivative"
      - "gaussian_HRV_GI_1st_derivative"
      - "raw_HRV_GI_1st_derivative"
      - "gaussian_HRV_PI_1st_derivative"
      - "raw_HRV_PI_1st_derivative"
      - "gaussian_HRV_C1d_1st_derivative"
      - "raw_HRV_C1d_1st_derivative"
      - "gaussian_HRV_C1a_1st_derivative"
      - "gaussian_HRV_C2d_1st_derivative"
      - "raw_HRV_C2d_1st_derivative"
      - "gaussian_HRV_C2a_1st_derivative"
      - "gaussian_HRV_Cd_1st_derivative_MIXED"
      - "raw_HRV_Cd_1st_derivative_MIXED"
      - "gaussian_HRV_Ca_1st_derivative"
      - "gaussian_HRV_DFA_alpha1_1st_derivative"
      - "raw_HRV_DFA_alpha1_1st_derivative"
      - "gaussian_HRV_MFDFA_alpha1_Width_1st_derivative"
      - "raw_HRV_MFDFA_alpha1_Width_1st_derivative"
      - "gaussian_HRV_MFDFA_alpha1_Peak_1st_derivative"
      - "raw_HRV_MFDFA_alpha1_Peak_1st_derivative"
      - "gaussian_HRV_MFDFA_alpha1_Mean_1st_derivative"
      - "raw_HRV_MFDFA_alpha1_Mean_1st_derivative"
      - "gaussian_HRV_MFDFA_alpha1_Max_1st_derivative"
      - "raw_HRV_MFDFA_alpha1_Max_1st_derivative"
      - "gaussian_HRV_MFDFA_alpha1_Delta_1st_derivative"
      - "raw_HRV_MFDFA_alpha1_Delta_1st_derivative"
      - "gaussian_HRV_MFDFA_alpha1_Asymmetry_1st_derivative"
      - "raw_HRV_MFDFA_alpha1_Asymmetry_1st_derivative"
      - "gaussian_HRV_MFDFA_alpha1_Fluctuation_1st_derivative"
      - "raw_HRV_MFDFA_alpha1_Fluctuation_1st_derivative"
      - "gaussian_HRV_ApEn_1st_derivative"
      - "raw_HRV_ApEn_1st_derivative"
      - "raw_HRV_ShanEn_1st_derivative"
      - "gaussian_HRV_FuzzyEn_1st_derivative"
      - "raw_HRV_FuzzyEn_1st_derivative"
      - "gaussian_HRV_CD_1st_derivative_UPPER"
      - "raw_HRV_CD_1st_derivative_UPPER"
      - "gaussian_HRV_HFD_1st_derivative"
      - "raw_HRV_HFD_1st_derivative"
      - "gaussian_HRV_KFD_1st_derivative"
      - "raw_HRV_KFD_1st_derivative"
      - "gaussian_HRV_LZC_1st_derivative"
      - "raw_HRV_LZC_1st_derivative"
      - "gaussian_total_power_1st_derivative"
      - "raw_total_power_1st_derivative"
      - "gaussian_normalized_power_1st_derivative"
      - "raw_normalized_power_1st_derivative"
      - "gaussian_LF_frequency_peak_1st_derivative"
      - "raw_LF_frequency_peak_1st_derivative"
      - "gaussian_HF_frequency_peak_1st_derivative"
      - "raw_HF_frequency_peak_1st_derivative"
      - "gaussian_HR_mean_1st_derivative"
      - "raw_HR_mean_1st_derivative"
      - "raw_HR_median_1st_derivative"
      - "gaussian_HR_max_1st_derivative"
      - "raw_HR_max_1st_derivative"
      - "gaussian_HR_min_1st_derivative"
      - "raw_HR_min_1st_derivative"
      - "gaussian_BVP_mean_1st_derivative"
      - "raw_BVP_mean_1st_derivative"
      - "gaussian_BVP_median_1st_derivative"
      - "raw_BVP_median_1st_derivative"
      - "gaussian_BVP_max_1st_derivative"
      - "raw_BVP_max_1st_derivative"
      - "raw_BVP_min_1st_derivative"
      - "gaussian_BVP_std_1st_derivative"
      - "raw_BVP_std_1st_derivative"
      - "gaussian_ACC_X_trimmed_mean_1st_derivative"
      - "raw_ACC_X_trimmed_mean_1st_derivative"
      - "gaussian_ACC_X_trimmed_max_1st_derivative"
      - "raw_ACC_X_trimmed_max_1st_derivative"
      - "raw_ACC_X_trimmed_IQR_1st_derivative"
      - "gaussian_ACC_Y_trimmed_mean_1st_derivative"
      - "raw_ACC_Y_trimmed_mean_1st_derivative"
      - "gaussian_ACC_Y_trimmed_max_1st_derivative"
      - "raw_ACC_Y_trimmed_max_1st_derivative"
      - "raw_ACC_Y_trimmed_IQR_1st_derivative"
      - "gaussian_ACC_Z_trimmed_mean_1st_derivative"
      - "raw_ACC_Z_trimmed_mean_1st_derivative"
      - "raw_ACC_X_MAD_trimmed_max_1st_derivative"
      - "gaussian_ACC_X_MAD_trimmed_IQR_1st_derivative"
      - "raw_ACC_X_MAD_trimmed_IQR_1st_derivative"
      - "raw_ACC_Y_MAD_trimmed_max_1st_derivative"
      - "raw_ACC_Y_MAD_trimmed_IQR_1st_derivative"
      - "gaussian_TEMP_mean_1st_derivative"
      - "raw_TEMP_mean_1st_derivative"
      - "raw_TEMP_max_1st_derivative"
      - "raw_TEMP_min_1st_derivative"
      - "gaussian_TEMP_std_1st_derivative"
      - "raw_TEMP_std_1st_derivative"
      - "gaussian_mean_SCR_Height_1st_derivative"
      - "raw_mean_SCR_Height_1st_derivative"
      - "gaussian_mean_SCR_RiseTime_1st_derivative"
      - "raw_mean_SCR_RiseTime_1st_derivative"
      - "gaussian_max_SCR_RiseTime_1st_derivative"
      - "raw_max_SCR_RiseTime_1st_derivative"
      - "gaussian_mean_SCR_RecoveryTime_1st_derivative"
      - "raw_mean_SCR_RecoveryTime_1st_derivative"
      - "gaussian_max_SCR_RecoveryTime_1st_derivative"
      - "raw_max_SCR_RecoveryTime_1st_derivative"
      
      # Artifact
      - "artifact"

      # other features
      - "sid"
      - "Sleep_Stage"
      - "Central_Apnea"
      - "Obstructive_Apnea"
      - "Multiple_Events"
      - "Hypopnea"
      - "AHI_Severity"
      - "Obesity"
      - "BMI"
      - "circadian_decay"
      - "circadian_linear"
      - "circadian_cosine"
      - "timestamp_start"