version: "1.0"
tables:
  activities:
    file_path: "dsa-pyhealth.csv"
    patient_id: "patient"
    timestamp: null
    attributes:
    - "activity"
    - "patient"
    - "segment"
    - "sample_id"
    - "T_xacc"
    - "RA_xacc"
    - "LA_xacc"
    - "RL_xacc"
    - "LL_xacc"
    - "T_xgyro"
    - "RA_xgyro"
    - "LA_xgyro"
    - "RL_xgyro"
    - "LL_xgyro"
    - "T_xmag"
    - "RA_xmag"
    - "LA_xmag"
    - "RL_xmag"
    - "LL_xmag"
    - "T_yacc"
    - "RA_yacc"
    - "LA_yacc"
    - "RL_yacc"
    - "LL_yacc"
    - "T_ygyro"
    - "RA_ygyro"
    - "LA_ygyro"
    - "RL_ygyro"
    - "LL_ygyro"
    - "T_ymag"
    - "RA_ymag"
    - "LA_ymag"
    - "RL_ymag"
    - "LL_ymag"
    - "T_zacc"
    - "RA_zacc"
    - "LA_zacc"
    - "RL_zacc"
    - "LL_zacc"
    - "T_zgyro"
    - "RA_zgyro"
    - "LA_zgyro"
    - "RL_zgyro"
    - "LL_zgyro"
    - "T_zmag"
    - "RA_zmag"
    - "LA_zmag"
    - "RL_zmag"
    - "LL_zmag"
