version: "5.0"
tables:
  eeg_tusz:
    file_path: "eeg_tusz-metadata-pyhealth.csv"
    patient_id: "subject_id"
    timestamp: null
    attributes:
    - "edf_file"
    - "session_id"
    - "slug_number"
    - "start_time"
    - "stop_time"
    - "label"
