version: "1.1.1"
tables:
  general_table:
    file_path: "general_table.csv"
    patient_id: "patientid"
    timestamp: "admissiontime"
    attributes:
      - "sex"
      - "age"
      - "discharge_status"

  merged_stage:
    file_path: "hirid-merged-pyhealth.csv"
    patient_id: "patientid"
    timestamp: "datetime"
    attributes:
      - "heart_rate"
      - "systolic_bp_invasive"
      - "diastolic_bp_invasive"
      - "mean_arterial_pressure"
      - "cardiac_output"
      - "spo2"
      - "rass"
      - "peak_inspiratory_pressure"
      - "lactate_arterial"
      - "lactate_venous"
      - "inr"
      - "serum_glucose"
      - "c_reactive_protein"
      - "dobutamine"
      - "milrinone"
      - "levosimendan"
      - "theophyllin"
      - "non_opioid_analgesics"

  observation_tables:
    file_path: "hirid-observations-pyhealth.csv"
    patient_id: "patientid"
    timestamp: "datetime"
    attributes:
      - "entertime"
      - "variableid"
      - "value"
      - "status"
      - "stringvalue"
      - "type"

  pharma_records:
    file_path: "hirid-pharma-pyhealth.csv"
    patient_id: "patientid"
    timestamp: "givenat"
    attributes:
      - "pharmaid"
      - "enteredentryat"
      - "givendose"
      - "cumulativedose"
      - "fluidamount_calc"
      - "cumulfluidamount_calc"
      - "doseunit"
      - "route"
      - "infusionid"
      - "typeid"
      - "subtypeid"
      - "recordstatus"

  imputed_stage:
    file_path: "hirid-imputed-pyhealth.csv"
    patient_id: "patientid"
    timestamp: null
    attributes:
      - "reldatetime"
      - "heart_rate"
      - "systolic_bp_invasive"
      - "diastolic_bp_invasive"
      - "mean_arterial_pressure"
      - "cardiac_output"
      - "spo2"
      - "rass"
      - "peak_inspiratory_pressure"
      - "lactate_arterial"
      - "lactate_venous"
      - "inr"
      - "serum_glucose"
      - "c_reactive_protein"
      - "dobutamine"
      - "milrinone"
      - "levosimendan"
      - "theophyllin"
      - "non_opioid_analgesics"
