version: "1.0"
tables:
  train:
    file_path: "icbhi-train-pyhealth.csv"
    patient_id: "patient_id"
    timestamp: null
    attributes:
      - "recording_id"
      - "cycle_id"
      - "audio_path"
      - "cycle_start"
      - "cycle_end"
      - "duration"
      - "has_crackles"
      - "has_wheezes"
      - "diagnosis"
      - "chest_location"
      - "acquisition_mode"
      - "equipment"
      - "age"
      - "sex"
      - "adult_bmi"
      - "child_weight"
      - "child_height"
      - "metadata_text"
  test:
    file_path: "icbhi-test-pyhealth.csv"
    patient_id: "patient_id"
    timestamp: null
    attributes:
      - "recording_id"
      - "cycle_id"
      - "audio_path"
      - "cycle_start"
      - "cycle_end"
      - "duration"
      - "has_crackles"
      - "has_wheezes"
      - "diagnosis"
      - "chest_location"
      - "acquisition_mode"
      - "equipment"
      - "age"
      - "sex"
      - "adult_bmi"
      - "child_weight"
      - "child_height"
      - "metadata_text"
