version: "1.0"
tables:
  metabric:
    file_path: "metabric_clinical.csv"
    patient_id: "PATIENT_ID"
    timestamp: null
    attributes:
      - "AGE_AT_DIAGNOSIS"
      - "OS_MONTHS"
      - "OS_STATUS"
      - "RFS_MONTHS"
      - "RFS_STATUS"
      - "INFERRED_MENOPAUSAL_STATE"
      - "TUMOR_SIZE"
      - "TUMOR_STAGE"
      - "NPI"
      - "CELLULARITY"
      - "CHEMOTHERAPY"
      - "ER_IHC"
      - "HER2_SNP6"
      - "HORMONE_THERAPY"
      - "INTCLUST"
      - "ONCOTREE_CODE"
      - "RADIO_THERAPY"
      - "THREEGENE"
      - "GRADE"
      - "TYPE_OF_BREAST_SURGERY"
      - "PR_STATUS"
      - "HER2_STATUS"
