version: "1.0"
tables:
  sbdh:
    file_path: "NOTEEVENTS.csv"
    patient_id: "SUBJECT_ID"
    timestamp: "CHARTTIME"
    join:
      - file_path: "MIMIC-SBDH.csv"
        "on": "ROW_ID"
        "on_right": "row_id"
        how: "inner"
        columns:
          - "sdoh_community_present"
          - "sdoh_community_absent"
          - "sdoh_education"
          - "sdoh_economics"
          - "sdoh_environment"
          - "behavior_alcohol"
          - "behavior_tobacco"
          - "behavior_drug"
    attributes:
      - "ROW_ID"
      - "SUBJECT_ID"
      - "CHARTTIME"
      - "TEXT"
      - "sdoh_community_present"
      - "sdoh_community_absent"
      - "sdoh_education"
      - "sdoh_economics"
      - "sdoh_environment"
      - "behavior_alcohol"
      - "behavior_tobacco"
      - "behavior_drug"
