version: "2.2"
tables:
  patients:
    file_path: "hosp/patients.csv.gz"
    patient_id: "subject_id"
    timestamp: null
    attributes:
      - "gender"
      - "anchor_age"
      - "anchor_year"
      - "anchor_year_group"
      - "dod"

  admissions:
    file_path: "hosp/admissions.csv.gz"
    patient_id: "subject_id"
    timestamp: "admittime"
    attributes:
      - "hadm_id"
      - "admission_type"
      - "admission_location"
      - "insurance"
      - "language"
      - "marital_status"
      - "race"
      - "discharge_location"
      - "dischtime"
      - "hospital_expire_flag"

  icustays:
    file_path: "icu/icustays.csv.gz"
    patient_id: "subject_id"
    timestamp: "intime"
    attributes:
      - "stay_id"
      - "first_careunit"
      - "last_careunit"
      - "outtime"

  diagnoses_icd:
    file_path: "hosp/diagnoses_icd.csv.gz"
    patient_id: "subject_id"
    join:
      - file_path: "hosp/admissions.csv.gz"
        "on": "hadm_id"
        how: "inner"
        columns:
          - "dischtime"
    timestamp: "dischtime"
    attributes:
      - "icd_code"
      - "icd_version"
      - "seq_num"

  procedures_icd:
    file_path: "hosp/procedures_icd.csv.gz"
    patient_id: "subject_id"
    join:
      - file_path: "hosp/admissions.csv.gz"
        "on": "hadm_id"
        how: "inner"
        columns:
          - "dischtime"
    timestamp: "dischtime"
    attributes:
      - "icd_code"
      - "icd_version"
      - "seq_num"

  prescriptions:
    file_path: "hosp/prescriptions.csv.gz"
    patient_id: "subject_id"
    timestamp: "starttime"
    attributes:
      - "drug"
      - "ndc"
      - "prod_strength"
      - "dose_val_rx"
      - "dose_unit_rx"
      - "route"
      - "stoptime"

  labevents:
    file_path: "hosp/labevents.csv.gz"
    patient_id: "subject_id"
    join:
      - file_path: "hosp/d_labitems.csv.gz"
        "on": "itemid"
        how: "inner"
        columns:
          - "label"
          - "fluid"
          - "category"
    timestamp: "charttime"
    attributes:
      - "itemid"
      - "label"
      - "fluid"
      - "category"
      - "value"
      - "valuenum"
      - "valueuom"
      - "flag"
      - "storetime"

  hcpcsevents:
    file_path: "hosp/hcpcsevents.csv.gz"
    patient_id: "subject_id"
    timestamp: "chartdate"
    attributes:
      - "hcpcs_cd"
      - "seq_num"
      - "short_description"
