version: "1.0"
tables:
  path_vqa:
    file_path: "path_vqa-metadata-pyhealth.csv"
    patient_id: "patient_id"
    timestamp: null
    attributes:
    - "path"
    - "question"
    - "answer"
    - "split"
    - "question_id"
    - "image_id"
    - "dataset"
