version: "1.0"
dataset_name: ph2

tables:
  ph2:
    file_path: ph2_metadata_pyhealth.csv
    patient_id: image_id
    visit_id: image_id
    timestamp: null
    timestamp_format: null
    attributes:
      - path
      - diagnosis
