version: "v4.0.0"
url: "https://github.com/synthetichealth/synthea/releases/download/v4.0.0/synthea-with-dependencies.jar"
sha256: "ed43c20ad40ba5c3bc724503a5af032715fe3c491620b766148e7c2361e6ecc1"

config_keys:
  base_directory: "exporter.baseDirectory"
  csv_export: "exporter.csv.export"

unsupported_export_flags:
  - "exporter.bfd.export"
  - "exporter.ccda.export"
  - "exporter.cdw.export"
  - "exporter.clinical_note.export"
  - "exporter.cpcds.export"
  - "exporter.fhir.export"
  - "exporter.fhir_dstu2.export"
  - "exporter.fhir_stu3.export"
  - "exporter.json.export"
  - "exporter.symptoms.csv.export"
  - "exporter.symptoms.text.export"
  - "exporter.text.export"
