name: pytest unittest action script 2

on: workflow_dispatch
  
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip' # caching pip dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Test with pytest
        run: |
          cd pyhealth/unittests
          pytest -rP
          
      - name: dataset pickles to upload
        run: |
          ls -al /home/runner/.cache/pyhealth/datasets/
      - name: upload datasets pickle
        uses: actions/upload-artifact@v3
        with:
          name: datasets
          path: /home/runner/.cache/pyhealth/datasets/
